### ISSUE TITLE
New Firmware for VTC Mini and Cuboid

### ISSUE THREAD

**Issue by bluenazgul** [TBXin/NFirmwareEditor#10]
Joyetech just released

FW3.02 for the VTC mini:
http://www.joyetech.com/mvr-software/?sid=155?age-verified=60bedaad49

FW3.12 for Cuboid:
http://www.joyetech.com/mvr-software/?sid=171

Both with official support for Logos

**Comment by TBXin** [comment]
Thanks for info.

Support for these firmwares will be available soon.

**Comment by TBXin** [comment]
Support was added in the release 3.7
