### ISSUE TITLE
device configuration not uploading changes

### ISSUE THREAD

**Issue by RenegadeTitan** [TBXin/NFirmwareEditor#101]
using rx2/3. already posted on myevic page but thought this might be more appropriate location. in nfe device configuration i can download most info but changes made in nfe do not change on device even though upload says completed. i tested temperature and base ohm. any ideas?

**Comment by TBXin** [comment]
myEvic is not compatible with Device Configuration, only "myEvic NFE Edition" is.
myEvic just simulating compatibility with Device Configuration, but DF structure is too different to correct work with Configuration utility.

**Comment by RenegadeTitan** [comment]
ok. thanks for quick response TBXin. maybe some day :)

**Comment by TBXin** [comment]
May be, may be ^^
