### ISSUE TITLE
Device configuration causes weird exclamation mark

### ISSUE THREAD

**Issue by puyamn** [TBXin/NFirmwareEditor#102]
After updating the myevic NFE settings on my VTC Mini a weird exclamation mark appears on the right of the battery indicator, which I can not find in the images of the firmware version. Any help or fix?
![2016 11 06 16 05 47](https://cloud.githubusercontent.com/assets/15175577/20038959/887c8e9e-a43c-11e6-9ee4-c0237d1cd10d.png) ![2016 11 06 16 19 33](https://cloud.githubusercontent.com/assets/15175577/20038960/88813476-a43c-11e6-87bd-46c6caea455d.png)

**Comment by TBXin** [comment]
Hello, this is LSL Mode = On. You can turn off it in the Expert menu on the device.

**Comment by puyamn** [comment]
I'm sorry, I just found the settings on device. Thanks for quick reply.
