### ISSUE TITLE
rx2/3 patch problem

### ISSUE THREAD

**Issue by snaperr** [TBXin/NFirmwareEditor#104]
hi I have RX2/3 and 4.12 soft and does not find me any patches, what is wrong?

**Comment by bluenazgul** [comment]
There are no Patches yet for the RX2/3 Firmware - also the NFirmwareEditor Developer is not the Developer for Patches

**Comment by snaperr** [comment]
So, why i see patch in folder (rx23 4.12) NFE version 5.1

**Comment by SEEKNDESTROY** [comment]
myEvic firmware has all the patches you need and some https://github.com/ClockSelect/myevic

**Comment by TBXin** [comment]
You see folder, because NFE automatically create folders for each firmware that knows. 
But in this case folder will be empty.
