### ISSUE TITLE
[question] "!" near battery icon

### ISSUE THREAD

**Issue by l4bor** [TBXin/NFirmwareEditor#105]
What the "!" near battery icon on MY eVic vTwo 80w / myEvic NFE Edition (build 161107)

---

Появился восклицательный знак ( ! ) возле иконки заряда батареи, что это значит?

**Comment by TBXin** [comment]
Режим LSL включен. Выключить в Expert можно. Почитать о том что это можно в официальной теме на форуме: http://www.ecigtalk.ru/forum/f16/t101098.html
