### ISSUE TITLE
MyEvic configuration not clickable

### ISSUE THREAD

**Issue by kablek** [TBXin/NFirmwareEditor#107]
Hi! 
I updated to 6.0 and it seems that myevic configuration in NFE toolbox is unclickable. It doesn't even lightup when you hover above it with mouse.

**Comment by TBXin** [comment]
Hi,

I know. Can you read release info? :)

https://github.com/TBXin/NFirmwareEditor/releases/tag/6.0

Right after NFE Toolbox screenshot ;)

**Comment by bluenazgul** [comment]
"myevic" Configuration is not yet Part of NFE 6.0 @TBXin wrote this Clear inside the Release Info. 

@ClockSelect and @TBXin need to Team up to bring it to us. "myevic" User different Dataflash as "ArcticFox"

**Comment by kablek** [comment]
oh sorry my bad, I have misread the thing as I was scrolling :)
