### ISSUE TITLE
ArcticFox Configuration failed to connect if preheat relax time is greater than 10

### ISSUE THREAD

**Issue by Jsl-1** [TBXin/NFirmwareEditor#108]
Hi, 

First, thank's for all your work ! 
Just a small issue in ArcticFox Configuration utility :

**Issue Descriptions:**
ArcticFox Configuration failed to connect if preheat relax time is greater than 10, 
There's an exception in ProfileTabContent.cs Line 33 (PreheatDelayUpDown.Value = profile.PreheatDelay / 10m; )
The editor Maximum value is set to 10, but the firmware does not limit this value. 

**Steps to Reproduce:**
Configure profile preheat relax time with value greater than 10 on the box
Connect the box and launch ArcticFox Configuration utility

**Comment by TBXin** [comment]
Hi,

Thanks for report. Yeap, this is a bug.
Fixed in commit: 1a386d67d5337fd780a4ea8349e614c80c0dbae0

Another release will be available in a few days, but at this moment you should set preheat delay lower than 10 sec to get working configuration utility.
