### ISSUE TITLE
Editor need a fix

### ISSUE THREAD

**Issue by StormtrooperBF** [TBXin/NFirmwareEditor#11]
With the new firmware it is possible to place pictures onto the Cuboid and the VTC-Mini interface. However these logos are hidden somewhere in the firmware, which cannot be retrieved by an editor to edit them. Can you please fix this?

**Comment by TBXin** [comment]
Hello,

Logo stored not in the firmware.
Logos are located in the memory area, which is outside the firmware area.

So, you never can't edit they while edition firmware file.

**Comment by StormtrooperBF** [comment]
Is it possible that we will receive an export function so we can edit the pictures as usual and save them as bitmap? That is the only thing i see which could make it possible.

**Comment by TBXin** [comment]
You can use Joyetech Updater Software to upload a custom image.
There is no way to download previously uploaded image.

**Comment by bluenazgul** [comment]
I belive what StormtrooperBF mean is an "Export to BMP" inside NFirmwareEditor so we are able to extract the Logo we want from older Firmware we created an will be able to use this Image with the Joyetech Updater

**Comment by StormtrooperBF** [comment]
This is exactly what I mean.
Thx bluenazgul

**Comment by TBXin** [comment]
Okay, this is possible. I will add this idea to the NFE todo list.

**Comment by jd0yle** [comment]
Seconded... would be a really handy feature

**Comment by TBXin** [comment]
Look at 3.71 release.
