### ISSUE TITLE
how to set maximum wattage on arcticfox?

### ISSUE THREAD

**Issue by mirko93s** [TBXin/NFirmwareEditor#111]
Can i set 100w like old patches?

**Comment by TBXin** [comment]
Maximum wattage is limited by your device, e.g.  for VTC Mini is 75w, for cuboid is 200w and so on.

**Comment by mirko93s** [comment]
Hi, thanks for the early answer, With patches I mod vtwo mini from 75 to 100w on ofw 4.02

**Comment by TBXin** [comment]
The theoretical maximum for VTwo mini is 92.5 (3.7V * 25A) watts, and yes, this is only theoretical. In real life you device with fresh batteries can give to you this wattage a very little amount of time.
No one has repealed the laws of physics.

**Comment by mirko93s** [comment]
So there's a way to increase max wattage? can I mod the bin if you kindly tell me what code line I need to see.
p.s. I translate the firmware in italian but some words are longer then english, can I add some more space to strings?

**Comment by TBXin** [comment]
You can't increase max wattage in the ArcticFox firmware.
And also you can't increase length of strings.

**Comment by mirko93s** [comment]
Ok, thanks anyway and congratulations for this amazing firmware. Sorry to bother you.

**Comment by TBXin** [comment]
No problem! I glad to hear that you like our firmware.
