### ISSUE TITLE
ArcticFox Configuration tool won't connect

### ISSUE THREAD

**Issue by cyris69** [TBXin/NFirmwareEditor#112]
**Issue Descriptions:**
ArcticFox Configuration tool does not connect to device. NFE Toolbox is 6.0
Here is a screenshot of all it does
http://i.imgur.com/AtHIkNW.png
The rest of the program works fine inlcuding live status
**Steps to Reproduce:**
For me running it with or without rx2/3 plugged in does it for me as I have never gotten that feature to work. Firmware is working fine on the device and is build 161205

**Comment by TBXin** [comment]
Hello,

If you decide to use nightly builds of the ArcticFox Firmware, you also should use nightly builds of the NFE Toolbox.

Link to the nightly builds of the NFE Toolbox you can get at the main page of this repository.

**Comment by cyris69** [comment]
My bad, I can't remember where I got the device build to be honest. I'll look here for the nightly tool build.

**Comment by TBXin** [comment]
which builds you are using? toolbox + arcticfox

**Comment by cyris69** [comment]
Sorry for the delay in response. NFirmwareEditor v6.0.34 since you mentioned I was on a nightly. Also, not sure if it's just a visual thing but when you lock the ohm it still changes on screen as the coil heats up.

**Comment by TBXin** [comment]
COIL or RES ?

**Comment by maelstrom2001** [comment]
@cyris69 Do you remember the behavior of COIL line in genuine Joyetech firmwares? Here is the same. While you pressing fire button, there is realtime resistance. Locking resistance means that mod will not ask you every time "is this new coil or same?" when resistance was changed slightly. But the appearance is close to stock firmwares: saved/locked Ohms in standby, and the real while heats up.
