### ISSUE TITLE
ArcticFox Puff cut-off

### ISSUE THREAD

**Issue by mirko93s** [TBXin/NFirmwareEditor#114]
fw:161209a
Hi, I tried to set cut-off but there isn't any difference, I can smoke over the selected time anyway.
Is that a bug or I'm mistaking something?

**Comment by TBXin** [comment]
Hi,

What value you have set?

**Comment by TBXin** [comment]
Try this build: https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/af_161212.bin

**Comment by mirko93s** [comment]
Hi, I tried 2 seconds but with 161212 it works perfectly on any selected time.
Thanks a lot!
