### ISSUE TITLE
Nfirmware Editor button grayed out in Toolbox

### ISSUE THREAD

**Issue by Starbuck3733T** [TBXin/NFirmwareEditor#115]
I can't get the myEvic configuration button to do anything, my mod is plugged in and screenshooter works fine, but the button for myEvic config is not clickable.  the config editor in V5.1 still works. Running latest build of myevic (downloaded today 2016-12-15.)

Any ideas?

**Comment by TBXin** [comment]
That's fine.

**Comment by Starbuck3733T** [comment]
This is the expected behavior? Thanks.

(I guess I should try articfox...)

**Comment by TBXin** [comment]
Yes, myEvic configuration utility is not developed yet

**Comment by Starbuck3733T** [comment]
Thank you very much for the super quick answer.  I'll stick with 5.1 for now.

**Comment by TBXin** [comment]
It's your choice, but I must admit that configuration utility from 5.1 is not designed for myEvic firmware. You can ruine all your settings

**Comment by Starbuck3733T** [comment]
yeah i've done that a few times. I just now got temperature control dialed in and working right so I'm nervous to switch firmwares.  I'm using the 'sweet' algo for TC and I have idea if articfox will behave similarly.

great work on the project though!
