### ISSUE TITLE
[Question] myEvic configuration support and VTC Mini - Expand 1st and 2nd line too #106

### ISSUE THREAD

**Issue by BigBadBlackWolf** [TBXin/NFirmwareEditor#117]
When is myEvic configuration supported and what is with the announcement from #106 "VTC Mini - Expand 1st and 2nd line too" - "will release our firmware in which you can change every line, even battery line using our configuration utility."

**Comment by TBXin** [comment]
1. I dont know.
2. [ArcticFox](https://github.com/maelstrom2001/ArcticFox) firmware is released for a long time.

**Comment by BigBadBlackWolf** [comment]
I know the ArcticFox has appeared, but so far this is not compatible with the myEvic firmware, since NFE Tool does not support myEvic configuration yet.

**Comment by TBXin** [comment]
Ehm... ArcticFox and myEvic are two different firmwares...
If you want line customization in myEvic like we make in the ArcticFox you should ask @ClockSelect make it. 
This kind of things should be done in both: firmware and configuration utility.

**Comment by BigBadBlackWolf** [comment]
Okay, Thanks!
I ask @ClockSelect

**Comment by nbraunstein** [comment]
Has @ClockSelect been working with you on making this a possibility?
