### ISSUE TITLE
[ArcticFox Configuration] - Can't connect

### ISSUE THREAD

**Issue by glennyy44** [TBXin/NFirmwareEditor#118]
hello,

it keeps saying connect device whith articfox 161219
what can i do?
![screenshot_7](https://cloud.githubusercontent.com/assets/24717571/21427812/0059e8e2-c857-11e6-87ed-00fd666cbfe3.png)

**Comment by TBXin** [comment]
What firmware are you using?

**Comment by glennyy44** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/24717571/21428516/a64ef528-c85a-11e6-9e4d-540f123438ad.png)

**Comment by TBXin** [comment]
So what?
Did you upload ArcticFox 161221 firmware to your device?
