### ISSUE TITLE
Stat export?

### ISSUE THREAD

**Issue by MoDuLah** [TBXin/NFirmwareEditor#120]
**Issue Descriptions:**
It would be nice to have some data about use of the device on excel.
CSV or xls can help with some lab-researches

**Comment by TBXin** [comment]
Concretize for beginning what you want.

**Comment by MoDuLah** [comment]
Average Watts, Average Puff duration, Total Vape time, Total Puff Counter, Device name, Firmware version.

**Comment by MoDuLah** [comment]
i was using this back in the Evic supreme and normal Evic days.
![screenshot_520](https://cloud.githubusercontent.com/assets/7404959/21468558/8a4aca42-ca20-11e6-8201-7277912c2f9d.png)
