### ISSUE TITLE
False possitive?

### ISSUE THREAD

**Issue by MoDuLah** [TBXin/NFirmwareEditor#121]
**Issue Descriptions:**
Downloaded from http://nfeteam.org/
**Steps to Reproduce:**
![image](https://cloud.githubusercontent.com/assets/7404959/21635201/f7d5a022-d264-11e6-873c-74f428c68982.png)

**Comment by TBXin** [comment]
https://virustotal.com/en/file/3ffbdd3c2c73531efc26b6155c6735352f6705b6f5344848fc4c1666c2dcb104/analysis/
