### ISSUE TITLE
Updated firmware is incompatible with older version configuration

### ISSUE THREAD

**Issue by techfixpros** [TBXin/NFirmwareEditor#122]
**Issue Descriptions:**
Cannot load a 161223 configuration on rx200s updated to 170103

**Steps to Reproduce:**
Upgraded from 161223 to 170103
Attempt to reload a configuration saved from 161223
Failed with a message stating I cannot load a configuration for a future version

**Comment by TBXin** [comment]
This is okay.
Saved configuration files from old firmware are not compatible with newer firmware.
