### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by trz3c1** [TBXin/NFirmwareEditor#124]
**Issue Descriptions:**
Hi there. After connecting my eVic VTC mini vis USB cable that came with my mod I get this massage (file attached
![error](https://cloud.githubusercontent.com/assets/24993063/21752816/572da9e8-d5df-11e6-9971-d2fdaa510076.jpg)
) Can anyone help me?
**Steps to Reproduce:**

**Comment by TBXin** [comment]
Your firmware?

**Comment by trz3c1** [comment]
3.03

**Comment by TBXin** [comment]
And what you want to accomplish by running the configuration utility for the ArcticFox firmware? 
That your 3,03 magically become ArctixFox firmware or what?

If you want to get working configuration utility you must first install ArcticFox firmware to your device.
