### ISSUE TITLE
Wismec Rx300

### ISSUE THREAD

**Issue by GGoldRock2k** [TBXin/NFirmwareEditor#126]
Do you gonna add Wismec RX300 to edit the firmware, as I already got it and want to edit it.

**Comment by maelstrom2001** [comment]
[RX300 5.04.zip](https://github.com/TBXin/NFirmwareEditor/files/693829/RX300.5.04.zip)
Download and unpack RX300 5.04.xml to Definitions folder.

**Comment by uhfnet** [comment]
Could you please also provide definitions for La Petite box by Vaponaute if possible? Seems to be identical to the VTC Mini, considering Vaponaute has a firmware v3.03 for download.

Thanks and sorry for hijacking the thread, thought it would be better than opening a new issue!

**Comment by TBXin** [comment]
@uhfnet where we can download La Petite box firmware?

**Comment by uhfnet** [comment]
@TBXin you can find a download link for the stock firmware here:

https://vaponaute.com/en/aircrafts/61-la-petite-box.html

Apparently, they have decided to host the firmware on Google Drive. Not very professional, but at least the device itself seems promising...

Thanks again!

**Comment by TBXin** [comment]
@uhfnet oh my god! thanks, I could not even think that download link will be made in the form of plain text ... without any indications...

**Comment by maelstrom2001** [comment]
@uhfnet Extract attached file to Definitions folder:
[La_Petite_Box_V3.03.zip](https://github.com/TBXin/NFirmwareEditor/files/706233/La_Petite_Box_V3.03.zip)

Actually, it will add 2nd strings block only, automatic recognition works fine.
