### ISSUE TITLE
[Possible bug?] Spikes in live battery voltage reading in device monitor.

### ISSUE THREAD

**Issue by sandbagjohnny** [TBXin/NFirmwareEditor#127]
Great job on this software suite, many options are nice :)

**Issue Descriptions:**

I'm reporting a possible problem with power over USB. I've got two eLeaf Pico's, bought 4 months apart, the first one in June 2016 and the other in November 2016. In device monitor, the voltage reading spikes from whatever the battery voltage is, to 5.12v, whenever the device is fired.

**Steps to Reproduce:**

[Pico A is set to power mode. Voltage spikes are circled in red.](http://imgur.com/T1pUTao)

[Pico B is set to TC PI mode. Voltage spikes are circled in red.](http://imgur.com/81tQnij)

**Comment by TBXin** [comment]
Thanks,

This spikes are result of the bad quality ADC and him noise.
Device Monitor just visualize data, that device send.

**Comment by sandbagjohnny** [comment]
Thank you.
