### ISSUE TITLE
[Vtwo Mini] Changing batteries, resetting stats and confirming "old coil" causes firing at 30W.

### ISSUE THREAD

**Issue by forkoz** [TBXin/NFirmwareEditor#130]
I'm running the 1/16 release on my vtwo mini and using a 1.4 ohm coil with SS316L. When I change batteries, reset stats and keep the old coil the mod fires at 30W instead of the 10 it was set to. I have to go into toolbox and re-upload the profile for it to stop. If I select "new" coil it gives a TCR error and will not fire.

[fire.csv.txt](https://github.com/TBXin/NFirmwareEditor/files/709352/fire.csv.txt)
![2017 01 16 14 37 31](https://cloud.githubusercontent.com/assets/12354546/21998266/6a67917a-dbf9-11e6-8f60-05861acc5eb6.png)

**Comment by maelstrom2001** [comment]
30 W is standard value for TCR Check procedure. When you changed coil/restart box/select another TC profile etc. box will check your coil on TCR. It starts from 30 to 40 W regarding selected temperature settings in profile. Your coil is not passing this check, 'cause resistance grows higher than 1,5 Ohms.

**Comment by TBXin** [comment]
You should ask questions about ArcticFox here: https://github.com/maelstrom2001/ArcticFox/issues
