### ISSUE TITLE
RX200 Splash Screen

### ISSUE THREAD

**Issue by FromDerik** [TBXin/NFirmwareEditor#136]
I've designed what i wanted to display and added the splash screen patch and saved the firmware but it does not show up on my device. Any idea why?

**Comment by TBXin** [comment]
Nope. 

Use this firmware: https://github.com/maelstrom2001/ArcticFox and get rid of depricated patches.

**Comment by FromDerik** [comment]
Apparently I just cant read and didn't realize it took 15 seconds to show on screen. How can I make it display sooner?
