### ISSUE TITLE
Old vtc mini 3.01 patches

### ISSUE THREAD

**Issue by delchrys** [TBXin/NFirmwareEditor#14]
Hi,

how can i use my old 3.01 patches with the new 3.02 firmware.
I would like to use the display brightness and some other patches, but they are not compatible anymore.
How can i fix this???

**Comment by TBXin** [comment]
Hello,

You can't. Patches are created exclusively for a specific firmware.
If you know assembler, you can port your own. But it seems to me that you do not know it :)
So, i'd recommend to you rollback your device to 3.01 firmware.

**Comment by delchrys** [comment]
i'll have to wait then until someone ports them to 3.02.
or i have to figure out the new adresses so i can rewrite the patches

**Comment by TBXin** [comment]
it is your choice, so i can't decide for you.
Also, patch-makers that i knew tell me, that they will not porting patches from 3.01 to 3.02.

**Comment by delchrys** [comment]
why don't they port to 3.02??

**Comment by TBXin** [comment]
No sense.
3.02 and 3.01 are same for end-user, except custom logos.
But for 3.01 already has been patch, that doing same things.

**Comment by delchrys** [comment]
i liked the 3.02 function of selectable logo on/off. combining the temp modes. And the logo instead of POWER and still showing watt when button pressed. 3.01 patches don't have those options.

**Comment by TBXin** [comment]
I can't help you. I don't create patches.

**Comment by delchrys** [comment]
ok thanks for the info anyway
