### ISSUE TITLE
Missing button in "Screenshooter"

### ISSUE THREAD

**Issue by XXMiToXX** [TBXin/NFirmwareEditor#148]
Hi,

is not an issue, it is only a "nice to have" option....

In the "Firmware updater" is a Cancel button, if you click this button it goes back to Main GUI.
In the "Screenshooter" there is NO button like is. You have to click the "X". ;)

Best regards
Mirko

![1](https://cloud.githubusercontent.com/assets/25363319/22364077/0cd44052-e46f-11e6-81b3-6abc5c6b02f7.jpg)
![12](https://cloud.githubusercontent.com/assets/25363319/22364078/0f1c6812-e46f-11e6-8012-c24a588cf1bc.jpg)

**Comment by TBXin** [comment]
> In the "Screenshooter" there is NO button like is. You have to click the "X". ;)

Or you can just press Esc button ^^

**Comment by XXMiToXX** [comment]
> Or you can just press Esc button ^^

Yes, if you knows that it works. But the button is intuitive and user friendly... ;)

**Comment by TBXin** [comment]
Done in the nightly builds.

![](http://i.imgur.com/Frqer0I.png)

**Comment by Daveee10** [comment]
Just a small thing, but IMO the Close button instead of Cancel would better.
