### ISSUE TITLE
Cuboid 3.12 Strings Block 2

### ISSUE THREAD

**Issue by candyman2903** [TBXin/NFirmwareEditor#15]
Hello, when I load the Cuboid v3.12 in NFirmwareEditor so will not appear in the string block 2 readable. In 3.7 I do not have the error.

![image](https://cloud.githubusercontent.com/assets/18519607/14768575/2e1c28f0-0a46-11e6-89eb-597b389c42b0.png)

**Comment by TBXin** [comment]
Hello.

In the release 3.71 slightly changed image loading algorithm.

You can see, that images in the block2 starts from 0x04, and not from 0x01 as should.
There are a little bug in the firmware definition that i just fixed.

Fixed Definition.xml file you can take here:
https://github.com/TBXin/NFirmwareEditor/blob/master/src/NFirmwareEditor/Definitions.xml

**Comment by candyman2903** [comment]
Thanks
