### ISSUE TITLE
[Request] Check build version within the program

### ISSUE THREAD

**Issue by FrankBKK** [TBXin/NFirmwareEditor#156]
Would be a great idea to be able to check the build version of the NFirmwareEditor or NToolbox from within the software.

**Comment by TBXin** [comment]
Build version of what?

**Comment by smok-e** [comment]
He means the build version of NToolbox, like  "Ntoolbox build 6.4.65" could be in the about screen

**Comment by TBXin** [comment]
Build last number just for internal purpose.

NToolbox version located here:

![](http://i.imgur.com/1Wiu2hP.png)

6.4 - is a NFE pack release version, based on the NFE version.

![](http://i.imgur.com/pEDUzrJ.png)

Anyway, released versions doesn't have build numbers, just major and minor.
