### ISSUE TITLE
Keep getting "Unable to download device settings" on Cuboid and Joytech TC100W

### ISSUE THREAD

**Issue by reflog** [TBXin/NFirmwareEditor#157]
Tried NFirmwareEditor-v6.4.0, since there is no log file, there's no more details I can provide.
How can I see what's causing this?

My system is win10 x64

**Comment by TBXin** [comment]
Because you are using not ArcticFox firmware.

**Comment by reflog** [comment]
Silly me, didn't understand that I need to flash it first before running the config :)
Thanks! 👍
