### ISSUE TITLE
Evic Vtc Patches

### ISSUE THREAD

**Issue by MoDuLah** [TBXin/NFirmwareEditor#16]
After trying some of them. I've seen that many are not compatible even with standalone.
Would be nice to see them updated for 3.02 firmware.

**Comment by TBXin** [comment]
https://github.com/TBXin/NFirmwareEditor/issues/14

**Comment by MoDuLah** [comment]
no no no.. i mean skip modes for example is not compatible on a 3.01 firmware.

**Comment by TBXin** [comment]
I gave you a link for this reason:
"patch-makers that i knew tell me, that they will not porting patches from 3.01 to 3.02."
"I don't create patches."

All patches for 3.01 are compatible with 'stock' firmware. If it is not true for you, that means, that you have not the original firmware file.
![](http://i.imgur.com/4gWramY.png)

**Comment by MoDuLah** [comment]
ok thank you for your help.
