### ISSUE TITLE
Adaptation of language packages

### ISSUE THREAD

**Issue by BigBadBlackWolf** [TBXin/NFirmwareEditor#173]
Since several questions were asked, why the myEvic button does not work in NFE Toolbox, the language packages should be adapted by a small change. Here is my suggestion for the English language pack:

// NToolbox Window
Toolbox.MainWindow.ArcticFoxConfigurationButton=ArcticFox Configuration
Toolbox.MainWindow.MyEvicConfigurationButton=myEvic Configuration\n(not supported yet)

and for the German language pack:

**Comment by BigBadBlackWolf** [comment]
// NToolbox Window
Toolbox.MainWindow.ArcticFoxConfigurationButton=ArcticFox konfigurieren
Toolbox.MainWindow.MyEvicConfigurationButton=myEvic konfigurieren\n(derzeit inaktiv)


All other language packages please also adjust.

**Comment by BigBadBlackWolf** [comment]
Or we leave this button completely away, as long as myevic is not supported. If this is the case, it can be inserted again. Thus, no requests are made by users why this button does not work.

**Comment by MoDuLah** [comment]
Greek:
// NToolbox Window
Toolbox.MainWindow.ArcticFoxConfigurationButton=Ρυθμίσεις ArcticFox
Toolbox.MainWindow.MyEvicConfigurationButton=Ρυθμίσεις myEvic\n(Δεν υποστηρίζεται ακόμα)
