### ISSUE TITLE
Bitmap Export in 3.71

### ISSUE THREAD

**Issue by bluenazgul** [TBXin/NFirmwareEditor#18]
Improvement:
- add "save as" dialog

Issue:
- Bitmaps saved as 24-Bit not monochrom

**Comment by TBXin** [comment]
This is a problem? :) 
nobody asked create monochrome bitmaps.

**Comment by bluenazgul** [comment]
OK, not an issue ;) lets change to imporvement ;)

**Comment by TBXin** [comment]
For what purpose you want 1bit bmp files?

**Comment by bluenazgul** [comment]
As example to make old (VTC 3.01) Firmware images compatible with the the new Joyetech Updater and Stock FW3.02

**Comment by TBXin** [comment]
For this purpose you can use any external image converter.
Even MS Paint can do this job: open one bmp and save in another format.

**Comment by TBXin** [comment]
In the next release export will be in the 1bbp indexed bitmap format.
