### ISSUE TITLE
Pico Dual - Recognize Device Bug

### ISSUE THREAD

**Issue by westor7** [TBXin/NFirmwareEditor#182]
Hello,

I had just buy the Pico Dual and when i place the USB cable the program cannot recognize the device, i had try it with the default Eleaf program and it recognized so i assume it's program issue.

Check this video to reproduce it: https://goo.gl/XT2DlI

- Thanks!

**Comment by TBXin** [comment]
@westor7 

Hello,

You should install ArcticFox firmware to get working ArcticFox configuration, i think this is obviously.

And Eleaf program is not configuration utility, it's firmware updater. You can press "Firmware Updater" button in the NToolbox and see that all are working fine. And one thing - you can install ArcticFox firmware only via NToolbox - Firmware Updater.

Best regards.

**Comment by westor7** [comment]
Yes but the problem when i use Firmware Updater it says that:

https://goo.gl/s630RL

**Comment by TBXin** [comment]
That is not problem, just missing correlation between PID (product identifier) and the real name.
The name of the device for convenience only, it is not affect anything.

> It shouldn't say Unknown Device yes?

I will fix this behavior later. Also need to add names for eVic Primo and some other devices.

**Comment by TBXin** [comment]
You can try latest [nightly build](https://ci.appveyor.com/project/TBXin/nfirmwareeditor/build/artifacts).
