### ISSUE TITLE
NToolbox: High CPU usage with Device Monitor

### ISSUE THREAD

**Issue by snigel** [TBXin/NFirmwareEditor#192]
When I use the device monitor the cpu usage creeps up until it consumes one core. From then it only becomes slower over time until it has to be restarted. It seems like increasing the X axis to 60 seconds make this happen faster. 15 minutes of run time is probably enough.

I've reproduced this several times on two different machines, Win 7 64bit and Win 10 64bit, together with an Eleaf iPower 80w.

**Comment by TBXin** [comment]
Hi,

What is your processor?

**Comment by snigel** [comment]
Win 7 64bit: Intel i7 6820HQ
Win 10 64bit: Intel i5 860

**Comment by snigel** [comment]
I checked more. Resized the window and set X scale to 60 seconds.
Took me about 5 minutes to spike one core.

Windows can be a bit tricky with showing that a core goes full, manually setting affinity for a process shows this more clearly.

**Comment by GnFlala** [comment]
I have the exact same problem. After a while cpu usage is high (goes up to 25 % when affinity is on all cores and 100% if it is on one core.). Device monitor is laggy after that happens.
