### ISSUE TITLE
[ADD FEATURE] Device Monitor Always show Coil Temp while using TC

### ISSUE THREAD

**Issue by GnFlala** [TBXin/NFirmwareEditor#193]
Hello. 

Would it be possible since we have live resistance measurement always on to have also coil temp always on and not only when we fire? 

Thanks.

**Comment by TBXin** [comment]
Hello,

Because device is calculating temperature only when "Fire" button is pressed.
Device Monitor only shows what the device sends.

**Comment by GnFlala** [comment]
Thanks for clarifying this man. Understood and thanks for replying.
