### ISSUE TITLE
NFirmware editor for RX300?

### ISSUE THREAD

**Issue by Echo113** [TBXin/NFirmwareEditor#195]
Ive copied the rx300 5.04.xml file posted on the other page to the Directories but im still getting unable to load firmware. No one definition is not appropriate for the selected firmware file.
![error](https://cloud.githubusercontent.com/assets/26468656/24015086/b9d34898-0a5d-11e7-97f2-5292ca2c0ca0.png)

**Comment by maelstrom2001** [comment]
Yep, firmware was updated, use attached definition for new binary.

[RX300 5.04 (13.01.2017).zip](https://github.com/TBXin/NFirmwareEditor/files/848882/RX300.5.04.13.01.2017.zip)

**Comment by Echo113** [comment]
That worked! Thanks! Do you happen to know how to invert the white squares around the ohms, Volts, etc?
![5_2_8](https://cloud.githubusercontent.com/assets/26468656/24016771/cef80a32-0a63-11e7-8ecc-1228efbf2b86.jpg)

**Comment by maelstrom2001** [comment]
> how to invert the white squares

By modifying firmware. Glyphs are drawn inverted at that places, need to replace calls of drawing procedures to regular, without inversion.

**Comment by Echo113** [comment]
Yea I know that much but the doesn't seem to be a bmp to invert. I've tried inverting literally everything. It must be coded to be white.
