### ISSUE TITLE
Support for Wismec Predator 228?

### ISSUE THREAD

**Issue by El-Grasa** [TBXin/NFirmwareEditor#199]
Hi,
First, let me say thanks for all the work you've done and continue to do on this awesome project. Much respect.

Will you be adding support for the Wismec Predator? I don't have one but the firmware looks just like the RX300 version.

Thanks

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by maelstrom2001** [comment]
Unpack attached XML to Definitions folder.

[Predator 5.04.zip](https://github.com/TBXin/NFirmwareEditor/files/869261/Predator.5.04.zip)

**Comment by El-Grasa** [comment]
Wow! Thanks for all your work.
