### ISSUE TITLE
3.01_3rd_line_aio.patch - clear save resistance by holding fire when 3rd line is selected.

### ISSUE THREAD

**Issue by traviswparker** [TBXin/NFirmwareEditor#2]
For some 3rd line info (PUFF, TIME) you can clear the counter by holding fire with the 3rd line selected. 

Could the saved resistance be cleared by holding fire when the 3rd line is selected? I've tried the 2/4 click patches and the keylock replacement. 2/4 click is too easy to trigger and I'd rather not replace keylock. 

Thanks!

**Comment by TBXin** [comment]
Thanks for your feedback.
Unfortunately i am not the author of patches. 
I will pass your wishes to the author of the patch.
