### ISSUE TITLE
Eleaf iStick Pico TC 75 Watt

### ISSUE THREAD

**Issue by bluenazgul** [TBXin/NFirmwareEditor#20]
Would it possible to add the "upgradable" Eleaf iStick Pico TC 75 Watt too?

**Comment by TBXin** [comment]
When eleaf published their firmware...

**Comment by spado92** [comment]
An iStick Pico firmware and device ID [got posted over here](https://github.com/Ban3/python-evic/issues/12#issuecomment-214047082) :)

**Comment by TBXin** [comment]
Thanks for link.
But there is not firmware file, just dataflash dump, but is useful too.

**Comment by spado92** [comment]
My bad. Sooner or later I guess they'll release an update for the Pico and the Presa TC100W...
