### ISSUE TITLE
Chinese localization-CN.LPACK.TXT

### ISSUE THREAD

**Issue by vojaly** [TBXin/NFirmwareEditor#204]
**Issue Descriptions:**
CN.LPACK.TXT TEXT
**Steps to Reproduce:**
Sample：

// Shared
Toolbox.Shared.SecondString=秒（注意！选择后，盒子将自动开始点火。）
Toolbox.Shared.SecondsString=秒

// NToolbox Window
Toolbox.MainWindow.ArcticFoxConfigurationButton=盒子配置
Toolbox.MainWindow.MyEvicConfigurationButton=我的设备配置
Toolbox.MainWindow.DeviceMonitorButton=盒子状态监控
Toolbox.MainWindow.ScreenshooterButton=屏幕设置
Toolbox.MainWindow.FirmwareUpdaterButton=固件升级
Toolbox.MainWindow.AboutLink=说明和连接

[CN.lpack.txt](https://github.com/TBXin/NFirmwareEditor/files/879113/CN.lpack.txt)
[CN.lpack.txt](https://github.com/TBXin/NFirmwareEditor/files/879114/CN.lpack.txt)

**Comment by TBXin** [comment]
Closed because of significant changes in lpack files.
