### ISSUE TITLE
Portuguese BR Translate PRBR.lpack.txt

### ISSUE THREAD

**Issue by RonaldoRisso** [TBXin/NFirmwareEditor#206]
// Shared
Toolbox.Shared.SecondString=segundo
Toolbox.Shared.SecondsString=segundos

// NToolbox Window
Toolbox.MainWindow.ArcticFoxConfigurationButton=Configuração Arcticfox
Toolbox.MainWindow.MyEvicConfigurationButton=Configuração myEvic
Toolbox.MainWindow.DeviceMonitorButton=Monitor Dispositivo
Toolbox.MainWindow.ScreenshooterButton=Captura de Tela
Toolbox.MainWindow.FirmwareUpdaterButton=Configuração de Firmware
Toolbox.MainWindow.AboutLink=Informação && Links

Toolbox.MainWindow.Tray.ShowToolbox=Mostrar Tela NFE Toolbox
Toolbox.MainWindow.Tray.ArcticFoxConfigurationWhenDeviceConnected=Abrir o Configurador ArcticFox com o dispositivo conectado.
Toolbox.MainWindow.Tray.TimeSync=Sincronizar relogio quando o dispositivo está conectado
Toolbox.MainWindow.Tray.StartWithWindows=Abrir caixa de ferramentas de NFE ao iniciar Windows
Toolbox.MainWindow.Tray.Exit=Sair

// ArcticFox Configuration Window
Toolbox.ArcticFoxConfiguration.Message.ConnectDevice=Conecte o dispositivo com\n\nArcticFox\n[{0}]\n\nfirmware mais recente
Toolbox.ArcticFoxConfiguration.Message.DownloadingSettings=Baixar ajustes de...
Toolbox.ArcticFoxConfiguration.Message.OutdatedToolbox=NFE Toolbox está desatualizado.\n\nPara continuar, por favor baixar\n\na última versão disponivel.
Toolbox.ArcticFoxConfiguration.Message.NoCompatibleUSBDevice=Não compativel com dispositivo USB conectado.\n\nPara continuar, por favor conecte um.\n\nSim já está conectado, Desconectar e Desconectar de novo. O cabo pode estar solto.
Toolbox.ArcticFoxConfiguration.Message.UnableToReadData=Não se pode baixar a configuração do dispositivo. Volte a conectar o dispositivo.

Toolbox.ArcticFoxConfiguration.Status.Device=Dispositivo 
Toolbox.ArcticFoxConfiguration.Status.Connected=Conectado
Toolbox.ArcticFoxConfiguration.Status.Disconnected=Desconectado
Toolbox.ArcticFoxConfiguration.Status.Ready=Feito
Toolbox.ArcticFoxConfiguration.Status.OperationCompleted=Operação completa

Toolbox.ArcticFoxConfiguration.ActiveProfileLabel=Ativo:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery1Label=Bateria 1:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery2Label=Bateria 2:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery3Label=Bateria 3:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery4Label=Bateria 4:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.BatteryEditButton=Modificar
Toolbox.ArcticFoxConfiguration.Advanced.Settings.BatteryModelLabel=Modelo Bateria:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.CheckTCRLabel=Verificar TCR:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.LSLLabel=Modo Light Sleep:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.PuffCutOffLabel=Puff Cut-Off:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.RCOBCLabel=RCOBC:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.ShuntCorrectionLabel=Correção Shunt:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.USBChargeLabel=Carga por USB:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.USBNoSleepLabel=Sem interrupção:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.X32Label=X32:
Toolbox.ArcticFoxConfiguration.AdvancedTab=Avançado
Toolbox.ArcticFoxConfiguration.BVOTab=BVO
Toolbox.ArcticFoxConfiguration.CircleScreenTab=Tema Circulos
Toolbox.ArcticFoxConfiguration.ClassicScreenTab=Tema Clasico
Toolbox.ArcticFoxConfiguration.ConfigurationButton=Configuração▾
Toolbox.ArcticFoxConfiguration.ConfigurationMenu.New=Novo
Toolbox.ArcticFoxConfiguration.ConfigurationMenu.Open=Abrir
Toolbox.ArcticFoxConfiguration.ConfigurationMenu.SaveAs=Salvar como
Toolbox.ArcticFoxConfiguration.ConnectAndDownloadLink=Conectar e baixar Configuração
Toolbox.ArcticFoxConfiguration.ControlsTab=Controles
Toolbox.ArcticFoxConfiguration.DownloadButton=Baixar Ajustes
Toolbox.ArcticFoxConfiguration.EnabledCheckBox=Ativado
Toolbox.ArcticFoxConfiguration.General.Controls.2ClicksLabel=2 Click:
Toolbox.ArcticFoxConfiguration.General.Controls.3ClicksLabel=3 Click:
Toolbox.ArcticFoxConfiguration.General.Controls.4ClicksLabel=4 Click:
Toolbox.ArcticFoxConfiguration.General.Controls.Power1WStepLabel=Subir/Descer 1W:
Toolbox.ArcticFoxConfiguration.General.Controls.SharedLabel=Modo Compartilhado - Função dos Botões de regulagem:
Toolbox.ArcticFoxConfiguration.General.Controls.TCModeClicksLabel=Modo TC - Função do Botão de acionamento:
Toolbox.ArcticFoxConfiguration.General.Controls.UpDownButtonsLabel=Modo:
Toolbox.ArcticFoxConfiguration.General.Controls.VWModeClicksLabel= Modo VW - Função do Botão de acionamento:
Toolbox.ArcticFoxConfiguration.General.Controls.WakeUpPlusMinusLabel=Ativar con + / - :
Toolbox.ArcticFoxConfiguration.General.Layout.Line1Label=Linha 1:
Toolbox.ArcticFoxConfiguration.General.Layout.Line2Label=Linha 2:
Toolbox.ArcticFoxConfiguration.General.Layout.Line3Label=Linha 3:
Toolbox.ArcticFoxConfiguration.General.Layout.Line4Label=Linha 4:
Toolbox.ArcticFoxConfiguration.General.Layout.PuffTimeLabel=Puff ⏱
Toolbox.ArcticFoxConfiguration.General.Layout.TCModeLayoutLabel=Disposição Linha TC:
Toolbox.ArcticFoxConfiguration.General.Layout.VWModeLayoutLabel=Disposição Linha VW:
Toolbox.ArcticFoxConfiguration.General.Screen.BrightnessLabel=Brilho:
Toolbox.ArcticFoxConfiguration.General.Screen.ChargeScreenLabel=Tela de carga:
Toolbox.ArcticFoxConfiguration.General.Screen.ClockTypeLabel=Tipo relogio:
Toolbox.ArcticFoxConfiguration.General.Screen.FlippedLabel=Inverter:
Toolbox.ArcticFoxConfiguration.General.Screen.IdleTimeLabel=Apagar Tela:
Toolbox.ArcticFoxConfiguration.General.Screen.MainScreenSkinLabel=Tema Tela:
Toolbox.ArcticFoxConfiguration.General.Screen.PuffScreenDelayLabel=Tempo da tela:
Toolbox.ArcticFoxConfiguration.General.Screen.ScreensaverTimeLabel=Protetor de tela:
Toolbox.ArcticFoxConfiguration.General.Screen.ShowClockLabel=Mostrar Relogio:
Toolbox.ArcticFoxConfiguration.General.Screen.ShowLogoLabel=Mostrar Logo:
Toolbox.ArcticFoxConfiguration.General.Screen.StealthModeLabel=Tela apagada:
Toolbox.ArcticFoxConfiguration.General.Screen.TooltipLabel=Para mostrar mais informações, colocar o mouse sobre o rotulo.
Toolbox.ArcticFoxConfiguration.General.Screen.UseClassicMenuLabel=Usar Menu clásico:
Toolbox.ArcticFoxConfiguration.General.Stats.PuffsCountLabel=Total de Puffs:
Toolbox.ArcticFoxConfiguration.General.Stats.PuffsTimeFormatLabel=Formato :
Toolbox.ArcticFoxConfiguration.General.Stats.TotalPuffsTimeLabel=Tempo Total:
Toolbox.ArcticFoxConfiguration.GeneralTab=Geral
Toolbox.ArcticFoxConfiguration.LayoutTab=Tema
Toolbox.ArcticFoxConfiguration.MaterialsTab=Materiais
Toolbox.ArcticFoxConfiguration.NewConfigurationLink=Criar nova Configuração
Toolbox.ArcticFoxConfiguration.OpenConfigurationLink=Abrir Configuração existente
Toolbox.ArcticFoxConfiguration.PowerCurvesTab=Curva Potencia (W) 
Toolbox.ArcticFoxConfiguration.Profile.CoilMaterialLabel=Coil Material:
Toolbox.ArcticFoxConfiguration.Profile.LockedCheckBox=Bloquear
Toolbox.ArcticFoxConfiguration.Profile.ModeLabel=Modo:
Toolbox.ArcticFoxConfiguration.Profile.NameLabel=Nome:
Toolbox.ArcticFoxConfiguration.Profile.PowerCurveEditButton=Modificar
Toolbox.ArcticFoxConfiguration.Profile.PowerLabel=Potencia (W):
Toolbox.ArcticFoxConfiguration.Profile.PreheatDelayLabel=Atraso Preheat:
Toolbox.ArcticFoxConfiguration.Profile.PreheatCurveLabel=Curva Preheat:
Toolbox.ArcticFoxConfiguration.Profile.PreheatPowerLabel=Curva Potencia (W):
Toolbox.ArcticFoxConfiguration.Profile.PreheatTimeLabel=Tempo Preheat:
Toolbox.ArcticFoxConfiguration.Profile.PreheatTypeLabel=Tipo Preheat:
Toolbox.ArcticFoxConfiguration.Profile.ProfileLabel=Perfil:
Toolbox.ArcticFoxConfiguration.Profile.ResistanceLabel=Resistencia:
Toolbox.ArcticFoxConfiguration.Profile.TCSetupButton=Ajustar
Toolbox.ArcticFoxConfiguration.Profile.TDomCheckBox=Temperatura Dominante 
Toolbox.ArcticFoxConfiguration.Profile.TemperatureLabel=Temperatura:
Toolbox.ArcticFoxConfiguration.Profile.TFREditButton=Modificar
Toolbox.ArcticFoxConfiguration.Profile.WattsLabel=W
Toolbox.ArcticFoxConfiguration.Profile.Mode.Power=Potencia (W)
Toolbox.ArcticFoxConfiguration.Profile.Mode.TempControl=Control Temp.
Toolbox.ArcticFoxConfiguration.ProfilesTab=Perfis
Toolbox.ArcticFoxConfiguration.ResetButton=Reiniciar Ajustes
Toolbox.ArcticFoxConfiguration.ScreenTab=Tela
Toolbox.ArcticFoxConfiguration.SecondsLabel=s
Toolbox.ArcticFoxConfiguration.SettingsTab=Configuração
Toolbox.ArcticFoxConfiguration.SmallScreenTab=Tela pequena
Toolbox.ArcticFoxConfiguration.SmartCheckBox=Perfil Inteligente
Toolbox.ArcticFoxConfiguration.StatsTab=Estatisticas
Toolbox.ArcticFoxConfiguration.UploadButton=Carregar Ajustes
Toolbox.ArcticFoxConfiguration.VoltsLabel=v

// Tooltips
Toolbox.ArcticFoxConfiguration.Tooltips.MainScreenSkin=Trocar o modelo da tela principal. Aplicavel só para dispositivos com tela maior (64x128).
Toolbox.ArcticFoxConfiguration.Tooltips.UseClassicMenu=Permite Trocar os perfis da maneira clásica: Power, Ni, Ti, etc.
Toolbox.ArcticFoxConfiguration.Tooltips.ShowLogo=Mostrar logo na tela principal.
Toolbox.ArcticFoxConfiguration.Tooltips.ShowClock=Ver relogio na tela inicial.
Toolbox.ArcticFoxConfiguration.Tooltips.MaxPuffTime=Tempo maximo da tela.
Toolbox.ArcticFoxConfiguration.Tooltips.ShuntCorrection=Correção da resistencia.
Toolbox.ArcticFoxConfiguration.Tooltips.X32=Habilita ou desabilita o uso do cristal X32 da placa.
Toolbox.ArcticFoxConfiguration.Tooltips.LightSleep=Light Sleep Mode, para dispositivos sem oscilador secundario manter RTC exato. Gasta um pouco mais de energia no modo de espera, o usuario será avisado pelo simbolo ! a direita do indicador de bateria.
Toolbox.ArcticFoxConfiguration.Tooltips.Rcobc=Reinicio do Contador em troca de bateria, reestabelecer as estatisticas.
Toolbox.ArcticFoxConfiguration.Tooltips.CheckTCR=Revise o material da bobina TCR, trocar esta opção para desativada pode eliminar o Error de TCR nas bobinas subohm.
Toolbox.ArcticFoxConfiguration.Tooltips.UsbCharge=Ativa ou desativa a carga por USB.
Toolbox.ArcticFoxConfiguration.Tooltips.UsbNoSleep=Não entrar em modo hibernar quando está conectado na USB.

// Static Dropdowns
Toolbox.ArcticFoxConfiguration.Profile.PreheatType.Absolute=Absoluto (W)
Toolbox.ArcticFoxConfiguration.Profile.PreheatType.Relative=Relativo (%)
Toolbox.ArcticFoxConfiguration.Profile.PreheatType.Curve=Curva
Toolbox.ArcticFoxConfiguration.InfoLines.NonDominant=Não dominante (Pwr / Temp)
Toolbox.ArcticFoxConfiguration.InfoLines.Volts=Volts
Toolbox.ArcticFoxConfiguration.InfoLines.OutputVolts=Tensão de saida
Toolbox.ArcticFoxConfiguration.InfoLines.OutputAmps=Corrente de saida
Toolbox.ArcticFoxConfiguration.InfoLines.Resistance=Resistencia
Toolbox.ArcticFoxConfiguration.InfoLines.LiveResistance=Resistencia real
Toolbox.ArcticFoxConfiguration.InfoLines.LinePuffs=Puff
Toolbox.ArcticFoxConfiguration.InfoLines.LinePuffsTime=Duração Puff
Toolbox.ArcticFoxConfiguration.InfoLines.BatteriesVolts=Tensão da batería
Toolbox.ArcticFoxConfiguration.InfoLines.DateTime=Data/Hora
Toolbox.ArcticFoxConfiguration.InfoLines.BoardTemp=Temperatura Placa
Toolbox.ArcticFoxConfiguration.InfoLines.LastPuffTime=Duração Ultimo Puff
Toolbox.ArcticFoxConfiguration.InfoLines.LastPower=Ultima Potencia (W)
Toolbox.ArcticFoxConfiguration.InfoLines.LastTemperature=Ultima Temperatura
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryIndicator=Bateria
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryIndicatorPercents=Bateria + %
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryIndicatorVolts=Bateria + V
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryPercents=Bateria %
Toolbox.ArcticFoxConfiguration.Skin.Classic=Clasico
Toolbox.ArcticFoxConfiguration.Skin.Circle=Circulos
Toolbox.ArcticFoxConfiguration.ChargeScreen.Classic=Clasico
Toolbox.ArcticFoxConfiguration.ChargeScreen.Extended=Extendido
Toolbox.ArcticFoxConfiguration.ClockType.Analog=Analogico
Toolbox.ArcticFoxConfiguration.ClockType.Digital=Digital
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.Off=Desligado
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.1Min=1 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.2Min=2 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.5Min=5 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.10Min=10 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.15Min=15 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.20Min=20 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.30Min=30 Min
Toolbox.ArcticFoxConfiguration.ClickActions.None=Nada
Toolbox.ArcticFoxConfiguration.ClickActions.Edit=Editar
Toolbox.ArcticFoxConfiguration.ClickActions.MainMenu=Menu principal
Toolbox.ArcticFoxConfiguration.ClickActions.PreheatMenu=Menu Preheat
Toolbox.ArcticFoxConfiguration.ClickActions.SelectProfile=Selecionar Perfil
Toolbox.ArcticFoxConfiguration.ClickActions.Edit Profile=Modificar Perfil
Toolbox.ArcticFoxConfiguration.ClickActions.TDom=TDom
Toolbox.ArcticFoxConfiguration.ClickActions.ShowClock=Mostrar Relogio
Toolbox.ArcticFoxConfiguration.ClickActions.InfoScreen=Tela de informação
Toolbox.ArcticFoxConfiguration.ClickActions.SmartOnOff=Ligar / Desligar (Smart)
Toolbox.ArcticFoxConfiguration.ClickActions.LLSOnOf=LSL Ligar / Desligar
Toolbox.ArcticFoxConfiguration.ClickActions.OnOff=Ligar / Desligar
Toolbox.ArcticFoxConfiguration.UpDownButtons.Normal=Normal
Toolbox.ArcticFoxConfiguration.UpDownButtons.Swapped=Trocar
Toolbox.ArcticFoxConfiguration.PuffsTimeFormat.Seconds=Segundos
Toolbox.ArcticFoxConfiguration.PuffsTimeFormat.HHMMSS=HH:MM:SS
Toolbox.ArcticFoxConfiguration.BatteryModel.Generic=Bateria Generica
Toolbox.ArcticFoxConfiguration.BatteryModel.Custom=Personalizado

// ArcticFox Configuration - PiRegulator Setup Window
Toolbox.ArcticFoxConfiguration.PiRegulator.SetupLabel=Configuração do Regulador-PI:
tor.SetupLabel=PI-Regulator SetupToolbox.ArcticFoxConfiguration.PiRegulator.UsePiRegulatorLabel=Regulador-PI
Toolbox.ArcticFoxConfiguration.PiRegulator.EnabledCheckBox=Ativado
Toolbox.ArcticFoxConfiguration.PiRegulator.RangeLabel=Intervalo:
Toolbox.ArcticFoxConfiguration.PiRegulator.PLabel=Valor P:
Toolbox.ArcticFoxConfiguration.PiRegulator.ILabel=Valor I:
Toolbox.ArcticFoxConfiguration.PiRegulator.SaveButton=Salvar
Toolbox.ArcticFoxConfiguration.PiRegulator.CancelButton=Cancelar

// ArcticFox Configuration - Power Curve Editor Window
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.NameLabel=Nombre Curva de Potencia (W):
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.ChartNameLabel=Curva de Potencia (W):
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.TimeLabel=Tiempo:
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.PercentLabel=Pct:
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.TimeScaleButton=Escala de Tiempo
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.SaveButton=Guardar
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.CancelButton=Cancelar

// ArcticFox Configuration - TFR Curve Editor Window
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.NameLabel=Perfil:
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.ChartNameLabel=Curva TFR:
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.FactorLabel=Fator:
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.ExportButton=Exportar
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.ImportButton=Importar
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.SaveButton=Salvar
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.CancelButton=Cancelar

// ArcticFox Configuration - Discharge Curve Editor Window
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ProfileLabel=Perfil:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ChartNameLabel=Curva de descarga:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.VoltsLabel=tensão:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.CutoffLabel=Corte:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.PresetsButton=Preestablecido
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ExportButton=Exportar
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ImportButton=Importar
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.SaveButton=Salvar
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.CancelButton=Cancelar

// Device Monitor Window
Toolbox.DeviceMonitor.SensorsLabel=Sensores:
Toolbox.DeviceMonitor.ControlsLabel=Controle:
Toolbox.DeviceMonitor.ChartNameLabel=Nome da linha:
Toolbox.DeviceMonitor.FollowButton=Acompanhar

Toolbox.DeviceMonitor.Battery1Label=Bateria 1:
Toolbox.DeviceMonitor.Battery2Label=Bateria 2:
Toolbox.DeviceMonitor.Battery3Label=Bateria 3:
Toolbox.DeviceMonitor.Battery4Label=Bateria 4:
Toolbox.DeviceMonitor.BatteryPackLabel=Conjunto das baterias:
Toolbox.DeviceMonitor.PowerLabel=Potencia (W):
Toolbox.DeviceMonitor.PowerSetLabel=Potencia (W) Ajustada:
Toolbox.DeviceMonitor.TemperatureLabel=Temperatura:
Toolbox.DeviceMonitor.TemperatureSetLabel=Temperatura Ajustada:
Toolbox.DeviceMonitor.OutputCurrentLabel=Corrente de Saida:
Toolbox.DeviceMonitor.OutputVoltageLabel=Tensão de Saida:
Toolbox.DeviceMonitor.ColdResistanceLabel=Resistencia a frio:
Toolbox.DeviceMonitor.LiveResistanceLabel=Resistencia Real:
Toolbox.DeviceMonitor.BoardTempLabel=Temperatura placa:

Toolbox.DeviceMonitor.PauseButton=Pausa
Toolbox.DeviceMonitor.PauseResumeButton=Continuar
Toolbox.DeviceMonitor.RecordButton=Gravar...
Toolbox.DeviceMonitor.RecordStopButton=Parar a gravação
Toolbox.DeviceMonitor.SetXScaleButton=Ajustar Scala X
Toolbox.DeviceMonitor.SetYScaleButton=Ajustar Scala Y
Toolbox.DeviceMonitor.PuffButton=Puff...
Toolbox.DeviceMonitor.ShowPufsBoundariesCheckBox=Mostrar limites de Puffs

// Screenshooter Window
Toolbox.Screenshooter.ScreenGroupLabel=Tela:
Toolbox.Screenshooter.ControlsGroupLabel=Controles:
Toolbox.Screenshooter.TakeScreenshotButton=Fazer Captura do Display
Toolbox.Screenshooter.SaveScreenshotButton=Salvar Captura do Display
Toolbox.Screenshooter.PixelSizeLabel=Tamanho do pixel, escala:
Toolbox.Screenshooter.TakeBeforeSaveLabel=Tirar antes de salvar:
Toolbox.Screenshooter.TakeBeforeSaveCheckbox=Ativado
Toolbox.Screenshooter.StartBroadcastButton=Mostrar ao vivo
Toolbox.Screenshooter.StopBroadcastButton=Parar ao vivo
Toolbox.Screenshooter.CancelButton=Cancelar

// Firmware Updater Window
Toolbox.FirmwareUpdater.DeviceInfoGroupLabel=Info Dispositivo:
Toolbox.FirmwareUpdater.DeviceNameLabel=Dispositivo:
Toolbox.FirmwareUpdater.FirmwareVersionLabel=Versão Firmware:
Toolbox.FirmwareUpdater.HardwareVersionLabel=Versão Hardware:
Toolbox.FirmwareUpdater.BootModeLabel=Modo de Boot:
Toolbox.FirmwareUpdater.ProgressGroupLabel=Progresso:
Toolbox.FirmwareUpdater.OperationsGroupLabel=Operação:
Toolbox.FirmwareUpdater.CommonTab=Comum
Toolbox.FirmwareUpdater.UpdateButton=Actualização do arquivo
Toolbox.FirmwareUpdater.DatalfashTab=Dataflash
Toolbox.FirmwareUpdater.ReadDataflashButton=Ler Dataflash
Toolbox.FirmwareUpdater.WriteDataflashButton=Escrever Dataflash
Toolbox.FirmwareUpdater.ResetDataFlashButton=Reiniciar Dataflash
Toolbox.FirmwareUpdater.AdvancedTab=Avançado
Toolbox.FirmwareUpdater.ChangeHWVerButton=Mudar versão HW
Toolbox.FirmwareUpdater.SwitchBootModeButton=Trocar tipo de Boot
Toolbox.FirmwareUpdater.CancelButton=Cancelar

Toolbox.FirmwareUpdater.Messages.DeviceIsReady=Dispositivo pronto.
Toolbox.FirmwareUpdater.Messages.WaitingForDevice=Esperando Dispositivo...
Toolbox.FirmwareUpdater.Messages.WaitingForDeviceAfterReset=Reiniciando o Dispositivo...
Toolbox.FirmwareUpdater.Messages.ReadingDataflash=Lendo Dataflash...
Toolbox.FirmwareUpdater.Messages.WritingDataflash=Escrevendo Dataflash...
Toolbox.FirmwareUpdater.Messages.RestartingDevice=Reiniciando o Dispositivo...
Toolbox.FirmwareUpdater.Messages.UploadingFirmware=Carregando o Firmware...
Toolbox.FirmwareUpdater.Messages.DataflashReadAndSave=Dataflash foi lido e salvo com exito no arquivo.
Toolbox.FirmwareUpdater.Messages.DataflashWritten=Dataflash salvo com exito.
Toolbox.FirmwareUpdater.Messages.DataflashReseted=Dataflash reiniciado.

**Comment by RonaldoRisso** [comment]
Revised and ok

**Comment by RonaldoRisso** [comment]
my contribution
Revised and ok

**Comment by TBXin** [comment]
Closed because of significant changes in lpack files.
