### ISSUE TITLE
NFirmwareEditor for Predator 228?

### ISSUE THREAD

**Issue by ETPNV13** [TBXin/NFirmwareEditor#208]
**Issue Descriptions:**
Just wondering when/if there is going to be an update to edit the Predator 228 firmware which I think is pretty similar to the rx300 firmware...wouldn't even ask but there has not been an update here in two months which is kind of weird/worrying to me since there is usually one like once a month
**Steps to Reproduce:**

**Comment by TBXin** [comment]
Hello,

Unzip file and put it in the "Definitions" directory, which is located near NFirmwareEditor.exe

[Predator 228 5.04.zip](https://github.com/TBXin/NFirmwareEditor/files/907509/Predator.228.5.04.zip)

**Comment by ETPNV13** [comment]
Worked perfectly, thank you much!

**Comment by ETPNV13** [comment]
Just another quick question, is there a way to get rid of the inverted portions and the arch over the wattage? I used to just delete the 4 circles on older firmware on other devices but there are no rectangular boxes and the arch is nowhere to be found either...If there is an easy way to do this that would be great but if not it is fine because as soon as arctic fox is compatible I am switching to that firmware anyways

**Comment by zxr750** [comment]
he dont work my mod...
[http://image.prntscr.com/image/aaf2eca6e46c4fefa761d9c218169f8d.png](url)

**Comment by zxr750** [comment]
[http://prnt.sc/f4rcne](url)

**Comment by TBXin** [comment]
This is an issue about editing OFW, not installing ArcticFox.
