### ISSUE TITLE
Add Estonian localization

### ISSUE THREAD

**Issue by sala91** [TBXin/NFirmwareEditor#209]
I helped out a little bit, produced estonian lang file. Plz include it. Can maintain it for future aswell.

// Shared
Toolbox.Shared.SecondString=sekund
Toolbox.Shared.SecondsString=sekundid

// NToolbox Window
Toolbox.MainWindow.ArcticFoxConfigurationButton=ArcticFox Konfiguratsioon
Toolbox.MainWindow.MyEvicConfigurationButton=myEvic Konfiguratsioon
Toolbox.MainWindow.DeviceMonitorButton=Seadme Monitor
Toolbox.MainWindow.ScreenshooterButton=Ekraanitõmmis
Toolbox.MainWindow.FirmwareUpdaterButton=Raudvara uuendaja
Toolbox.MainWindow.AboutLink=Asjast && Linke

Toolbox.MainWindow.Tray.ShowToolbox=Näita NFE Toolbox aken
Toolbox.MainWindow.Tray.ArcticFoxConfigurationWhenDeviceConnected=Ava ArcticFox Konfiguratsioon kui seade on ühendatud
Toolbox.MainWindow.Tray.ArcticFoxConfigurationWhenDeviceDisconnected=Sulge ArcticFox Konfiguratsioon kui seade on lahti ühendatud
Toolbox.MainWindow.Tray.TimeSync=Sünkroniseeri seadme aeg kui ta ühendatakse
Toolbox.MainWindow.Tray.StartWithWindows=Jooksuta NFE Toolbox kui Windows käivitub
Toolbox.MainWindow.Tray.Exit=Välju

// ArcticFox Configuration Window
Toolbox.ArcticFoxConfiguration.Message.ConnectDevice=Ühenda seade, millel on\n\nArcticFox\n[{0}]\n\nraudvara või uuem
Toolbox.ArcticFoxConfiguration.Message.DownloadingSettings=Laen seadeid...
Toolbox.ArcticFoxConfiguration.Message.OutdatedToolbox=NFE Toolbox is vana.\n\nEt jätkata, palun lae\n\nviimane väljalase alla.
Toolbox.ArcticFoxConfiguration.Message.NoCompatibleUSBDevice=Ühtegi ühilduvat USB seadet pole ühendatud.\n\nEt jätkata palun ühenda üks.\n\nKui üks on juba ühendatud, proovi lahti ühendada ja tagasi külge ühendada. Kaabel ei pruugi olla korraliult ühendatud.
Toolbox.ArcticFoxConfiguration.Message.UnableToReadData=Ei õnnestunud seadeid laadida. Palun proovi uuesti.

Toolbox.ArcticFoxConfiguration.Status.Device=Seade on
Toolbox.ArcticFoxConfiguration.Status.Connected=ühendatud
Toolbox.ArcticFoxConfiguration.Status.Disconnected=eemaldatud
Toolbox.ArcticFoxConfiguration.Status.Ready=Valmis
Toolbox.ArcticFoxConfiguration.Status.OperationCompleted=Operatsioon edukas

Toolbox.ArcticFoxConfiguration.ActiveProfileLabel=Aktiivne:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery1Label=Aku 1:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery2Label=Aku 2:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery3Label=Aku 3:
Toolbox.ArcticFoxConfiguration.Advanced.BVO.Battery4Label=Aku 4:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.BatteryEditButton=Muuda
Toolbox.ArcticFoxConfiguration.Advanced.Settings.BatteryModelLabel=Aku Mudel:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.CheckTCRLabel=Kontrolli TCR:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.LSLLabel=Kerge Sleep Mode:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.PuffCutOffLabel=Puff Cut-Off:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.RCOBCLabel=RCOBC:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.ShuntCorrectionLabel=Shunt parandus:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.USBChargeLabel=USB laadimine:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.USBNoSleepLabel=USB küljes ei maga:
Toolbox.ArcticFoxConfiguration.Advanced.Settings.X32Label=X32:
Toolbox.ArcticFoxConfiguration.AdvancedTab=Rohkem
Toolbox.ArcticFoxConfiguration.BVOTab=BVO
Toolbox.ArcticFoxConfiguration.CircleScreenTab=Ring ekraan
Toolbox.ArcticFoxConfiguration.ClassicScreenTab=Klassikaline ekraan
Toolbox.ArcticFoxConfiguration.ConfigurationButton=Konfiguratsioon▾
Toolbox.ArcticFoxConfiguration.ConfigurationMenu.New=Uus
Toolbox.ArcticFoxConfiguration.ConfigurationMenu.Open=Ava
Toolbox.ArcticFoxConfiguration.ConfigurationMenu.SaveAs=Salvesta kui
Toolbox.ArcticFoxConfiguration.ConnectAndDownloadLink=Ühenda ja lae seadistus
Toolbox.ArcticFoxConfiguration.ControlsTab=Juhtimine
Toolbox.ArcticFoxConfiguration.DownloadButton=&Lae seadistus
Toolbox.ArcticFoxConfiguration.EnabledCheckBox=Lubatud
Toolbox.ArcticFoxConfiguration.General.Controls.2ClicksLabel=2 klikki:
Toolbox.ArcticFoxConfiguration.General.Controls.3ClicksLabel=3 klikki:
Toolbox.ArcticFoxConfiguration.General.Controls.4ClicksLabel=4 klikki:
Toolbox.ArcticFoxConfiguration.General.Controls.Power1WStepLabel=Power 1W samm:
Toolbox.ArcticFoxConfiguration.General.Controls.SharedLabel=Jagautd:
Toolbox.ArcticFoxConfiguration.General.Controls.TCModeClicksLabel=TC Mode Fire nuppu multi klik:
Toolbox.ArcticFoxConfiguration.General.Controls.UpDownButtonsLabel=Up/Down nupud:
Toolbox.ArcticFoxConfiguration.General.Controls.VWModeClicksLabel=VW Mode Fire nuppu multi klik:
Toolbox.ArcticFoxConfiguration.General.Controls.WakeUpPlusMinusLabel=Ärata ülesse + / - :
Toolbox.ArcticFoxConfiguration.General.Layout.Line1Label=Rida 1:
Toolbox.ArcticFoxConfiguration.General.Layout.Line2Label=Rida 2:
Toolbox.ArcticFoxConfiguration.General.Layout.Line3Label=Rida 3:
Toolbox.ArcticFoxConfiguration.General.Layout.Line4Label=Rida 4:
Toolbox.ArcticFoxConfiguration.General.Layout.PuffTimeLabel=Puffi aeg
Toolbox.ArcticFoxConfiguration.General.Layout.TCModeLayoutLabel=TC Lines välimus:
Toolbox.ArcticFoxConfiguration.General.Layout.VWModeLayoutLabel=VW Lines välimus:
Toolbox.ArcticFoxConfiguration.General.Screen.BrightnessLabel=Taustvalgustus:
Toolbox.ArcticFoxConfiguration.General.Screen.ChargeScreenLabel=Laadimise ekraan:
Toolbox.ArcticFoxConfiguration.General.Screen.ClockTypeLabel=Kella tüüp:
Toolbox.ArcticFoxConfiguration.General.Screen.FlippedLabel=Tagurpidi:
Toolbox.ArcticFoxConfiguration.General.Screen.IdleTimeLabel=Niisama aeg:
Toolbox.ArcticFoxConfiguration.General.Screen.MainScreenSkinLabel=Pea ekraani välimus:
Toolbox.ArcticFoxConfiguration.General.Screen.PuffScreenDelayLabel=Puffi ekraani viide:
Toolbox.ArcticFoxConfiguration.General.Screen.ScreensaverTimeLabel=Erkaanisäästja aeg:
Toolbox.ArcticFoxConfiguration.General.Screen.ShowClockLabel=Näita kella:
Toolbox.ArcticFoxConfiguration.General.Screen.ShowLogoLabel=Näita logo:
Toolbox.ArcticFoxConfiguration.General.Screen.StealthModeLabel=Ekraan väljas:
Toolbox.ArcticFoxConfiguration.General.Screen.TooltipLabel=Liiguta hiirt kasti või teksti peale et näha rohkem infot.
Toolbox.ArcticFoxConfiguration.General.Screen.UseClassicMenuLabel=Kasuta klassikalist menüüd:
Toolbox.ArcticFoxConfiguration.General.Stats.PuffsCountLabel=Puffide lugeja:
Toolbox.ArcticFoxConfiguration.General.Stats.PuffsTimeFormatLabel=Puffs aja formaat:
Toolbox.ArcticFoxConfiguration.General.Stats.TotalPuffsTimeLabel=Kogu Puffide aeg:
Toolbox.ArcticFoxConfiguration.GeneralTab=Üldine
Toolbox.ArcticFoxConfiguration.LayoutTab=Välimus
Toolbox.ArcticFoxConfiguration.MaterialsTab=Materjalid
Toolbox.ArcticFoxConfiguration.NewConfigurationLink=Tekita uus konfiguratsioon
Toolbox.ArcticFoxConfiguration.OpenConfigurationLink=Ava eksisteeriv konfiguratsioon
Toolbox.ArcticFoxConfiguration.PowerCurvesTab=Jõu kurvid
Toolbox.ArcticFoxConfiguration.Profile.CoilMaterialLabel=Coili materjal:
Toolbox.ArcticFoxConfiguration.Profile.LockedCheckBox=Lukustatud
Toolbox.ArcticFoxConfiguration.Profile.ModeLabel=Mode:
Toolbox.ArcticFoxConfiguration.Profile.NameLabel=Nimi:
Toolbox.ArcticFoxConfiguration.Profile.PowerCurveEditButton=Muuda
Toolbox.ArcticFoxConfiguration.Profile.PowerLabel=Power:
Toolbox.ArcticFoxConfiguration.Profile.PreheatDelayLabel=Eelsoenduse Viide:
Toolbox.ArcticFoxConfiguration.Profile.PreheatCurveLabel=Eelsoenduse Kurv:
Toolbox.ArcticFoxConfiguration.Profile.PreheatPowerLabel=Eelsoenduse Power:
Toolbox.ArcticFoxConfiguration.Profile.PreheatTimeLabel=Eelsoenduse aeg:
Toolbox.ArcticFoxConfiguration.Profile.PreheatTypeLabel=Eelsoenduse tüüp:
Toolbox.ArcticFoxConfiguration.Profile.ProfileLabel=Profiil:
Toolbox.ArcticFoxConfiguration.Profile.ResistanceLabel=Takistus:
Toolbox.ArcticFoxConfiguration.Profile.TCSetupButton=Seadistus
Toolbox.ArcticFoxConfiguration.Profile.TDomCheckBox=Temperature Dominant
Toolbox.ArcticFoxConfiguration.Profile.TemperatureLabel=Temperatuur:
Toolbox.ArcticFoxConfiguration.Profile.TFREditButton=Muuda
Toolbox.ArcticFoxConfiguration.Profile.WattsLabel=W
Toolbox.ArcticFoxConfiguration.Profile.Mode.Power=Jõud
Toolbox.ArcticFoxConfiguration.Profile.Mode.TempControl=Temp. kontroll
Toolbox.ArcticFoxConfiguration.ProfilesTab=Profiilid
Toolbox.ArcticFoxConfiguration.ResetButton=Lähtesta seaded
Toolbox.ArcticFoxConfiguration.ScreenTab=Ekraan
Toolbox.ArcticFoxConfiguration.SecondsLabel=s
Toolbox.ArcticFoxConfiguration.SettingsTab=Seaded
Toolbox.ArcticFoxConfiguration.SmallScreenTab=Väike ekraan
Toolbox.ArcticFoxConfiguration.SmartCheckBox=Tark profiili valik
Toolbox.ArcticFoxConfiguration.StatsTab=Statistika
Toolbox.ArcticFoxConfiguration.UploadButton=&Salvesta seaded
Toolbox.ArcticFoxConfiguration.VoltsLabel=v

// Tooltips
Toolbox.ArcticFoxConfiguration.Tooltips.MainScreenSkin=Change main screen style. Applicable only for devices with big screen (64x128).
Toolbox.ArcticFoxConfiguration.Tooltips.UseClassicMenu=Allows to switch profiles in the classical way, like old modes: Power, Ni, Ti, etc.
Toolbox.ArcticFoxConfiguration.Tooltips.ShowLogo=Näita logo peaekraanil.
Toolbox.ArcticFoxConfiguration.Tooltips.ShowClock=Näita kella peaekraanil.
Toolbox.ArcticFoxConfiguration.Tooltips.MaxPuffTime=Maximum puffi aja parandus.
Toolbox.ArcticFoxConfiguration.Tooltips.ShuntCorrection=Ohm-meter parandus.
Toolbox.ArcticFoxConfiguration.Tooltips.X32=Lubab või keelab X32 kristalli kasutuse PCB'l.
Toolbox.ArcticFoxConfiguration.Tooltips.LightSleep=Kerge uni seadmetele ilma X32 kristallita (RX300)
Toolbox.ArcticFoxConfiguration.Tooltips.Rcobc=Nullib puffi koguse aku vahetusel.
Toolbox.ArcticFoxConfiguration.Tooltips.CheckTCR=Kontrilli coili materjali TCR, problemaatiline suurtemate coilidega
Toolbox.ArcticFoxConfiguration.Tooltips.UsbCharge=Lubab või keelab USB laadimise.
Toolbox.ArcticFoxConfiguration.Tooltips.UsbNoSleep=Ära mine magama kuniks ühendatud USB.

// Static Dropdowns
Toolbox.ArcticFoxConfiguration.Profile.PreheatType.Absolute=Absoluutne (W)
Toolbox.ArcticFoxConfiguration.Profile.PreheatType.Relative=Relatiivne (%)
Toolbox.ArcticFoxConfiguration.Profile.PreheatType.Curve=Kurv
Toolbox.ArcticFoxConfiguration.InfoLines.NonDominant=Non dominant (Pwr / Temp)
Toolbox.ArcticFoxConfiguration.InfoLines.Volts=Voldid
Toolbox.ArcticFoxConfiguration.InfoLines.OutputVolts=Väljund Voldid
Toolbox.ArcticFoxConfiguration.InfoLines.OutputAmps=Väljund Amprid
Toolbox.ArcticFoxConfiguration.InfoLines.Resistance=Takistus
Toolbox.ArcticFoxConfiguration.InfoLines.LiveResistance=Reaalne takistus
Toolbox.ArcticFoxConfiguration.InfoLines.LinePuffs=Puffid
Toolbox.ArcticFoxConfiguration.InfoLines.LinePuffsTime=Puffi aeg
Toolbox.ArcticFoxConfiguration.InfoLines.BatteriesVolts=Aku(s) Voldid
Toolbox.ArcticFoxConfiguration.InfoLines.DateTime=Päev/Kell
Toolbox.ArcticFoxConfiguration.InfoLines.BoardTemp=Emaplaadi Temperatuur
Toolbox.ArcticFoxConfiguration.InfoLines.LastPuffTime=Viimase puffi aeg
Toolbox.ArcticFoxConfiguration.InfoLines.LastPower=Viimane Power
Toolbox.ArcticFoxConfiguration.InfoLines.LastTemperature=Viimane Temperature
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryIndicator=Aku
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryIndicatorPercents=Aku + %
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryIndicatorVolts=Aku + V
Toolbox.ArcticFoxConfiguration.InfoLines.BatteryPercents=Aku %
Toolbox.ArcticFoxConfiguration.Skin.Classic=Klassikaline
Toolbox.ArcticFoxConfiguration.Skin.Circle=Ring
Toolbox.ArcticFoxConfiguration.ChargeScreen.Classic=Klassikaline
Toolbox.ArcticFoxConfiguration.ChargeScreen.Extended=Laiendatud
Toolbox.ArcticFoxConfiguration.ClockType.Analog=Analoog
Toolbox.ArcticFoxConfiguration.ClockType.Digital=Digitaalne
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.Off=Väljas
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.1Min=1 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.2Min=2 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.5Min=5 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.10Min=10 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.15Min=15 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.20Min=20 Min
Toolbox.ArcticFoxConfiguration.ScreenProtectionTime.30Min=30 Min
Toolbox.ArcticFoxConfiguration.ClickActions.None=Pole
Toolbox.ArcticFoxConfiguration.ClickActions.Edit=Muuda
Toolbox.ArcticFoxConfiguration.ClickActions.MainMenu=Peamenüü
Toolbox.ArcticFoxConfiguration.ClickActions.PreheatMenu=Eelsoenduse menüü
Toolbox.ArcticFoxConfiguration.ClickActions.SelectProfile=Vali profiil
Toolbox.ArcticFoxConfiguration.ClickActions.Edit Profile=Muuda profiili
Toolbox.ArcticFoxConfiguration.ClickActions.TDom=TDom
Toolbox.ArcticFoxConfiguration.ClickActions.ShowClock=Näita kella
Toolbox.ArcticFoxConfiguration.ClickActions.InfoScreen=Info ekraan
Toolbox.ArcticFoxConfiguration.ClickActions.ResetCounters=Nulli kaunterid
Toolbox.ArcticFoxConfiguration.ClickActions.SmartOnOff=Tark On / Off
Toolbox.ArcticFoxConfiguration.ClickActions.LLSOnOf=LSL On / Off
Toolbox.ArcticFoxConfiguration.ClickActions.OnOff=On / Off
Toolbox.ArcticFoxConfiguration.UpDownButtons.Normal=Normal
Toolbox.ArcticFoxConfiguration.UpDownButtons.Swapped=Vahetatud
Toolbox.ArcticFoxConfiguration.PuffsTimeFormat.Seconds=Seconds
Toolbox.ArcticFoxConfiguration.PuffsTimeFormat.HHMMSS=HH:MM:SS
Toolbox.ArcticFoxConfiguration.BatteryModel.Generic=Tavaline aku
Toolbox.ArcticFoxConfiguration.BatteryModel.Custom=Eriaku

// ArcticFox Configuration - PiRegulator Setup Window
Toolbox.ArcticFoxConfiguration.PiRegulator.SetupLabel=PI-Regulator seadistus:
Toolbox.ArcticFoxConfiguration.PiRegulator.UsePiRegulatorLabel=Use PI-Regulator:
Toolbox.ArcticFoxConfiguration.PiRegulator.EnabledCheckBox=Lubatud
Toolbox.ArcticFoxConfiguration.PiRegulator.RangeLabel=Vahemik:
Toolbox.ArcticFoxConfiguration.PiRegulator.PLabel=P väärtus:
Toolbox.ArcticFoxConfiguration.PiRegulator.ILabel=I väärtus:
Toolbox.ArcticFoxConfiguration.PiRegulator.SaveButton=Salvesta
Toolbox.ArcticFoxConfiguration.PiRegulator.CancelButton=Katkesta

// ArcticFox Configuration - Power Curve Editor Window
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.NameLabel=&Jõu Kurvi Nimi:
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.ChartNameLabel=Jõu Kurv:
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.TimeLabel=Aeg:
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.PercentLabel=Pct:
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.TimeScaleButton=Aja skaala
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.SaveButton=&Salvesta
Toolbox.ArcticFoxConfiguration.PowerCurveEditor.CancelButton=&Katkesta

// ArcticFox Configuration - TFR Curve Editor Window
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.NameLabel=&Profile:
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.ChartNameLabel=TFR Kurv:
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.FactorLabel=Faktor:
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.ExportButton=&Export
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.ImportButton=&Import
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.SaveButton=&Salvesta
Toolbox.ArcticFoxConfiguration.TFRCurveEditor.CancelButton=&Katkesta

// ArcticFox Configuration - Discharge Curve Editor Window
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ProfileLabel=Profile:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ChartNameLabel=Tühjakslaadimise kurv:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.VoltsLabel=Voldid:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.CutoffLabel=Katkestus:
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.PresetsButton=Seadistused
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ExportButton=Export
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.ImportButton=Import
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.SaveButton=Salvesta
Toolbox.ArcticFoxConfiguration.DischargeCurveEditor.CancelButton=Katkesta

// Device Monitor Window
Toolbox.DeviceMonitor.SensorsLabel=Sensorid:
Toolbox.DeviceMonitor.ControlsLabel=Kontroll:
Toolbox.DeviceMonitor.ChartNameLabel=Liini vaade:
Toolbox.DeviceMonitor.FollowButton=Jälgi

Toolbox.DeviceMonitor.Battery1Label=Aku1:
Toolbox.DeviceMonitor.Battery2Label=Aku2:
Toolbox.DeviceMonitor.Battery3Label=Aku3:
Toolbox.DeviceMonitor.Battery4Label=Aku4:
Toolbox.DeviceMonitor.BatteryPackLabel=Aku Pakk:
Toolbox.DeviceMonitor.PowerLabel=Power:
Toolbox.DeviceMonitor.PowerSetLabel=Power Set:
Toolbox.DeviceMonitor.TemperatureLabel=Temperatuur:
Toolbox.DeviceMonitor.TemperatureSetLabel=Temperatuur Säti:
Toolbox.DeviceMonitor.OutputCurrentLabel=Väljund Current:
Toolbox.DeviceMonitor.OutputVoltageLabel=Väljund Voltage:
Toolbox.DeviceMonitor.ColdResistanceLabel=Külm Takistus:
Toolbox.DeviceMonitor.LiveResistanceLabel=Reaal Takistus:
Toolbox.DeviceMonitor.BoardTempLabel=Emaplaadi Temperatuur:

Toolbox.DeviceMonitor.PauseButton=Paus
Toolbox.DeviceMonitor.PauseResumeButton=Jätka
Toolbox.DeviceMonitor.RecordButton=Salvesta...
Toolbox.DeviceMonitor.RecordStopButton=Lõpeta salvestamine
Toolbox.DeviceMonitor.SetXScaleButton=Säti X skaala
Toolbox.DeviceMonitor.SetYScaleButton=Säti Y skaala
Toolbox.DeviceMonitor.PuffButton=Puff...
Toolbox.DeviceMonitor.ShowPufsBoundariesCheckBox=Näita Puffi Piire

// Screenshooter Window
Toolbox.Screenshooter.ScreenGroupLabel=Erkaan:
Toolbox.Screenshooter.ControlsGroupLabel=Controls:
Toolbox.Screenshooter.TakeScreenshotButton=Tee ekraanitõmmis
Toolbox.Screenshooter.SaveScreenshotButton=Salvesta ekraanitõmmis
Toolbox.Screenshooter.PixelSizeLabel=Pixeli suuruse kordaja:
Toolbox.Screenshooter.TakeBeforeSaveLabel=Võta enne salvestamist:
Toolbox.Screenshooter.TakeBeforeSaveCheckbox=Lubatud
Toolbox.Screenshooter.StartBroadcastButton=Alusta saatmist
Toolbox.Screenshooter.StopBroadcastButton=Lõpeta saatmine
Toolbox.Screenshooter.CancelButton=Katkesta

// Firmware Updater Window
Toolbox.FirmwareUpdater.DeviceInfoGroupLabel=Seadme info:
Toolbox.FirmwareUpdater.DeviceNameLabel=Seadme nimi:
Toolbox.FirmwareUpdater.FirmwareVersionLabel=Raudvara versioon:
Toolbox.FirmwareUpdater.HardwareVersionLabel=Riistvara versioon:
Toolbox.FirmwareUpdater.BootModeLabel=Boot mode:
Toolbox.FirmwareUpdater.ProgressGroupLabel=Progress:
Toolbox.FirmwareUpdater.OperationsGroupLabel=Operatsioon:
Toolbox.FirmwareUpdater.CommonTab=Ühine
Toolbox.FirmwareUpdater.UpdateButton=Uuenda failist
Toolbox.FirmwareUpdater.DatalfashTab=Dataflash
Toolbox.FirmwareUpdater.ReadDataflashButton=Loe dataflash
Toolbox.FirmwareUpdater.WriteDataflashButton=Kirjuta dataflash
Toolbox.FirmwareUpdater.ResetDataFlashButton=Reset dataflash
Toolbox.FirmwareUpdater.AdvancedTab=Advanced
Toolbox.FirmwareUpdater.ChangeHWVerButton=Muuda HW versiooni
Toolbox.FirmwareUpdater.SwitchBootModeButton=Vaheta boot mode
Toolbox.FirmwareUpdater.CancelButton=Katkesta

Toolbox.FirmwareUpdater.Messages.DeviceIsReady=Seade on valmis.
Toolbox.FirmwareUpdater.Messages.WaitingForDevice=Ootame seadet...
Toolbox.FirmwareUpdater.Messages.WaitingForDeviceAfterReset=Ootame seadet peale resetti...
Toolbox.FirmwareUpdater.Messages.ReadingDataflash=Loen dataflash...
Toolbox.FirmwareUpdater.Messages.WritingDataflash=Kirjutan dataflash...
Toolbox.FirmwareUpdater.Messages.RestartingDevice=Taaskäivitan seadet...
Toolbox.FirmwareUpdater.Messages.UploadingFirmware=Uuendan tarkvara...
Toolbox.FirmwareUpdater.Messages.DataflashReadAndSave=Dataflash on edukalt loetud ja salvestatud faili.
Toolbox.FirmwareUpdater.Messages.DataflashWritten=Dataflash on edukalt kirjutatud.
Toolbox.FirmwareUpdater.Messages.DataflashReseted=Dataflash on edukalt resettitud.
Toolbox.FirmwareUpdater.Messages.FirmwareSuccessfullyUpdated=Raudvara edukalt uuendatud.
Toolbox.FirmwareUpdater.Messages.FirmwareUpdateFailed=Raudvara uuendamine kukkus läbi!
Toolbox.FirmwareUpdater.Messages.FirmwareUpdateFatalError=Ootamatu viga juhtus raudvara uuendamisel. Proovi uuesti.

**Comment by TBXin** [comment]
Closed because of significant changes in lpack files.
