### ISSUE TITLE
cks icon 200w firmware

### ISSUE THREAD

**Issue by rizanfauzan** [TBXin/NFirmwareEditor#210]
can you please add defenitions for cks icon 200w firmware
i need it because the firmware that based on vo chipset missing some string la coma, battery indicator, number 9, and make my mod display error
please
pardon my english

**Comment by TBXin** [comment]
Sorry but no.

This software is designed to open & edit only Joyetech based PCB's firmwares.
I don't know anything about VO chipset and their firmware.

**Comment by rizanfauzan** [comment]
thats a shame
thank you for replying though
i really appreciate it

**Comment by TBXin** [comment]
shame? Oo

**Comment by rizanfauzan** [comment]
sorry for my english
i mean it as im unlucky or something
i probably use the word wrong T_T

**Comment by TBXin** [comment]
Okay, bro :) 
Thanks for the explanation!

**Comment by maelstrom2001** [comment]
@rizanfauzan Look at title: "Firmware editor for vape devices from Joyetech, Wismec, Eleaf"
Do you think it's very simple and enough to add a single file to support a **completely different** device?

**Comment by rizanfauzan** [comment]
@maelstrom2001 sorry, because the title says "and so on" that i think its almost for most device
for the inconvenience im sorry to bother
im not trying to make users here mad
@TBXin sorry and thanks for understanding
