### ISSUE TITLE
Little grapphics issue in 7.0.1

### ISSUE THREAD

**Issue by smok-e** [TBXin/NFirmwareEditor#212]
in the german localisation you see some glitches in the shortcuts VW / TC tab in almost all boxes
where it says  "Feuer -" and "Feuer +" ,
even when I delete the space between the "Feuer" and "+"
the + is only in the "in standby" box not before the dropdownbox.

just a little glitch, but it doesn't make sense to shorten the word "Feuer" to make it fit better.

**Comment by TBXin** [comment]
Hello,

I can fix elements visible order to prevents lables to overlay comboboxes, but it stills not enough space for German localization ^^

![](http://i.imgur.com/cymTk6V.png)

I think you should keep "Fire" instead of "Feuer".
