### ISSUE TITLE
[Suggestion] Make String Editor resources list with previews

### ISSUE THREAD

**Issue by yvanovsk** [TBXin/NFirmwareEditor#23]
Hi!
Thanks for a great job!

I have a suggestion to make the strings editor resource list look like images resource list, when every list item has a small picture with a preview. This would simplify the process of navigation in string editor list.

Thanks in advance,
Удачи и спасибо.

**Comment by TBXin** [comment]
Hello,

Thanks for your feedback. Strings preview will be added in the next release.

![](http://i.imgur.com/ygrC8jO.png)

**Comment by yvanovsk** [comment]
Вот спасибо!
Thanks a lot!
