### ISSUE TITLE
[Suggestion] Free HEX code input mode in string editor

### ISSUE THREAD

**Issue by yvanovsk** [TBXin/NFirmwareEditor#24]
Hi!

I have a suggestion to have an additional mode for editing string resources. Right now this is implemented with a number of ComboBoxes/DropDownLists. I suggest to add an option to input HEX values to a simple TextBox in a format like "93 70 83 A6 D0 00 00 00" - this would increase the speed of Copy/Paste while editing the strings. Surely, this a Pro option and it requires a number of additional verification routines to implement (format correctness, max string length).

Thanks in advance,
Regards/

**Comment by TBXin** [comment]
Hello,

Yes, I keep this feature in mind, but I dont know exactly when it will be implemented.
