### ISSUE TITLE
[Suggestion] Patches tab - Add "Open in Editor" button

### ISSUE THREAD

**Issue by yvanovsk** [TBXin/NFirmwareEditor#25]
Hi!

It would be great to have a button in the Patches tab to open the selected patch in an editor. For rough implementation - Notepad, for pro - a configurable application of user desire.

Thanks in advance,
Regards.

**Comment by TBXin** [comment]
Hello,

This feature also will be available in the next release, but without user customizations.
This is mean that *.patch files will be open in the associated with this extension application.

**Comment by yvanovsk** [comment]
Nice!
Thank you!
