### ISSUE TITLE
[Suggestion] Dataflash offline edit

### ISSUE THREAD

**Issue by yvanovsk** [TBXin/NFirmwareEditor#27]
Hi!

Just an idea to do some research on how and what data is stored in dataflash to make it possible to edit some of the parameters on a PC.

Use case 1: Change TCR settings in user frendly software
Use case 2: Correct the save resistance for TC coil for those, who do not use a Patch  to reset it
Use case 3: IF some good person will make a Clock patch for devices like VTC mini we could use NFE to sync the time on every cable connection to overcome the fact that on every battery change clock would be reseted
Use case N: Set a new  "record" in FlappyBird

Furthermore, a system of XML plugins/definitions might be involved to make this option more community oriented.  

Thanks in advance,
Regards.

**Comment by ReservedField** [comment]
In case someone finds it useful, here's some [info on the 3.00 dataflash layout](http://pastebin.com/0H1yGQvF) I reversed some time ago. More (by another guy) [here](https://bitbucket.org/netman69/evicflash/src/565c519b150f0b01718c0ae8842f2c035f705457/dataflash.png?fileviewer=file-view-default) and [here](https://bitbucket.org/netman69/evicflash/src/565c519b150f0b01718c0ae8842f2c035f705457/dataflash_map_v3.txt?fileviewer=file-view-default).
