### ISSUE TITLE
[Suggestion] Support for RX200S

### ISSUE THREAD

**Issue by mroedel** [TBXin/NFirmwareEditor#35]
Is it possible to implement modifications for the RX200S?

**Comment by TBXin** [comment]
Yes, of course.
Did you have firmware file that you want to modify?

**Comment by mroedel** [comment]
Well, I Don't...
I hoped for some hacky tricks to extract the firmware ;)

**Comment by TBXin** [comment]
There is no such command to dump firmware from device.
So, support of the RX200S firmwares will be available as soon as Wismec will publish their updated firmware.
