### ISSUE TITLE
Patches not shown.

### ISSUE THREAD

**Issue by ferongr** [TBXin/NFirmwareEditor#38]
I downloaded NFirmwareEditor 4.01 from the releases and loaded the 3.10 firmware of the RX200. No patches show up on the Patches tab. The .patch files do exist in the proper directories.

**Comment by TBXin** [comment]
Look at the bottom right corner of the NFE. If you see "RX200 3.10 (24.05.2016)", i have bad news for you :) There are no patches for this version of firmware. You need previous 3.10 version.
Yes, Wismec released 2 different firmwares with one version.

**Comment by ferongr** [comment]
Welp. hope I find the zip containing the previous version somewhere.

**Comment by TBXin** [comment]
http://rgho.st/8nLnQX8Vw
