### ISSUE TITLE
Wismec RX200 3.10 update breaks NFirmwareEditor

### ISSUE THREAD

**Issue by olokos** [TBXin/NFirmwareEditor#4]
RX200 got updated to 3.10 and NFirmwareEditor can no longer read it. :(

**Comment by TBXin** [comment]
Just wait :) 
Support for new versions of the firmware must be added manually.

**Comment by olokos** [comment]
It was sort of a heads up, so you'd know that it's released. I have to say I'm amazed with your speed.
