### ISSUE TITLE
Cuboid 3.12

### ISSUE THREAD

**Issue by MYWARUK** [TBXin/NFirmwareEditor#41]
Hi there, 
When I had my Cuboid few months back, Before I sold it on, I was able to edit the official 3.12 firmware and able to use Patches and Resource Packs. I got another Cuboid, downloaded the 3.12 firmware, but now no Patches or Resource Packs are there, When I try to load them i get the message:

"Selected resource pack is incompatible with the loaded firmware.
Resource Pack is designed for: Cuboid 3.12
Opened Firmware is: Cuboid 3.12 (31.05.2016)"

If someone has a link to the older 3.12 that be great

Cheers for your work, great tool!

**Comment by TBXin** [comment]
Hello,

Here you are: http://rgho.st/7DqPjfpxS

**Comment by MYWARUK** [comment]
Thank you so much!

I'll keep that backed up.

Thank you again 👍
