### ISSUE TITLE
Error when loading the original wismec rx200s firmware

### ISSUE THREAD

**Issue by badummtss** [TBXin/NFirmwareEditor#45]
how can i solve the problem??? [<a href="http://www.directupload.net/file/d/4403/hkq7suib_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/160701/temp/hkq7suib.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>](url)

**Comment by TBXin** [comment]
Hello,

This is not original 4.0 firmware. Wismec released few days ago another firmware with a same version.
Add to your definitions.xml file following node:

	<FirmwareDefinition Name="RX200S 4.00 (27.06.2016)">
		<Marker Offset="0x90" Bytes="0xD9 0x21" />
		<Marker Offset="0xC0" Bytes="0xA9 0x6D" />
		<ImageTable1>
			<OffsetFrom>0xC274</OffsetFrom>
			<OffsetTo>0xC674</OffsetTo>
		</ImageTable1>
		<ImageTable2>
			<OffsetFrom>0xA3E4</OffsetFrom>
			<OffsetTo>0xA7E4</OffsetTo>
		</ImageTable2>
		<StringTable1 TwoByteChars="true">
			<OffsetFrom>0xC778</OffsetFrom>
			<OffsetTo>0xC9B5</OffsetTo>
		</StringTable1>
		<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
	</FirmwareDefinition>

**Comment by badummtss** [comment]
Thank you @TBXin now it works.
