### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Insane88** [TBXin/NFirmwareEditor#5]
Hi,

Does this software works on Cuboid with H/W version :1.02 ? Because i cannot seem to make it work , no matter what i try.

Thank you!

**Comment by TBXin** [comment]
Hi,

This application can edit the firmware and load them into the device.
What exactly do you want to do?

**Comment by Insane88** [comment]
edit/update/modify the font. or apply patches. I should mention i tried on my friends Cuboid H/W version 1.01 and worked perfectly.

**Comment by TBXin** [comment]
I do not know about which patches you are talking about, but there is almost no patches for cuboid.
Also, you need to know, that there are two image blocks in the firmware. 
And most likely you are modifying, only the first.

**Comment by Insane88** [comment]
It may be my fault for downloading a .bin file from the internet and expect it to work on my mod, but i was a little baffled when it worked on my friends mod ( HW 1.01) https://www.youtube.com/watch?v=Uqd4PwbE_RI 
Thank you for your input so quickly , i will try as suggested and edit both fields first.

**Comment by Insane88** [comment]
I have managed to successfully change the font by copying the first images block to the second on the firmware listed on this site http://pictape.com/devices/custom-firmware-for-the-evic-vtc-mini-cuboid-rx200.php

Thank you !
