### ISSUE TITLE
[Request] Manual Coil Erase for VTwo Mini

### ISSUE THREAD

**Issue by bfnk** [TBXin/NFirmwareEditor#53]
Hello, 

Please create a patch for the VTwo Mini that allows us to erase saved coils. It is really the most important patch I  can think of. Thank you very much for your work so far!

Regards

**Comment by gdimakis** [comment]
Get the VTCfont! It has every patch you need including the coil erase.
It supports the vtwon mini 4.02 firmware
http://www.ecigtalk.ru/forum/f16/t101158.html
use the translation chrome feature.
NFirmwareEditor has no vtc support anymore

**Comment by bfnk** [comment]
Thank you very much for this!!

**Comment by gdimakis** [comment]
I'm happy ypou had the time to get it!1 cheers!
