### ISSUE TITLE
[Request] Patch RX2/3

### ISSUE THREAD

**Issue by bluenazgul** [TBXin/NFirmwareEditor#57]
Since we allready have the Firmware for the Wismec Reuleaux RX2/3
http://www.wismec.com/software/wismec-tc-software-for-upgrading-reuleaux-rx23/

Would it allready be possible to port the Patches (1W Steps / 100% Brightness) from the RX200S for the Rx2/3?

**Comment by maelstrom2001** [comment]
@bluenazgul Please test:
https://dl.dropboxusercontent.com/u/43399149/VTC/tmp/RX23_4.12_brightness100.patch
https://dl.dropboxusercontent.com/u/43399149/VTC/tmp/RX23_4.12_1w.patch

**Comment by bluenazgul** [comment]
Wow, thanks @maelstrom2001 both patches are working

Tested both seperate and together.

**Comment by TBXin** [comment]
Both patches were added to the NFE repository:

![](http://i.imgur.com/p5OFaQS.png)
