### ISSUE TITLE
Read Batteries correctly on RX200S

### ISSUE THREAD

**Issue by wastez** [TBXin/NFirmwareEditor#58]
Is there a way to improve the battery check on the RX200S?
So that the voltage is shown correctly?

**Comment by TBXin** [comment]
This is a hardware issue.

**Comment by wastez** [comment]
A generell issue? Or a issue just on my device?

**Comment by TBXin** [comment]
This is a general issue for all 2+ battery devices from joyetech, eleaf, wismec.
