### ISSUE TITLE
[REQUEST] Can you add various patches for egrip 2  v4.03

### ISSUE THREAD

**Issue by deddy84** [TBXin/NFirmwareEditor#59]
Hi, please can you add patches for joyetech egrip 2. I found another patches in nfirmwareeditor folder, but dont work whit egrip2. Thank you!

**Comment by TBXin** [comment]
There are no patches for eGrip II firmwares.

**Comment by deddy84** [comment]
I know! I found egrip 2 folder, but there is no patches in it. Can you add some patches in next release?

**Comment by TBXin** [comment]
Patches is not my prerogative, also no one of us does not have eGrip device to test any modifications.
Maybe you know what patches do you need? :)

**Comment by SaschaK** [comment]
There are some folders without content. They are placeholders. If patches exists they took them in. But no patches exist.

**Comment by deddy84** [comment]
Need: percentage battery, max display brightness, 1 degree increase/decrease in tc mode, digital clock in screensaver. 
Of course, i can test patches and report to you. 
(sorry for my english)
