### ISSUE TITLE
Editor not editing

### ISSUE THREAD

**Issue by Keba4** [TBXin/NFirmwareEditor#6]
Hi there,
I can change the external firmware from other people in my eVic VTC mini, but can´t change my own. I rewrite pixels, save as a new file and when I send it to mine eVic, nothing changes. Do you have an idea what am I doing wrong? Thank you, Jakub.

**Comment by TBXin** [comment]
Hello,

You need to change images in both blocks. Different HW versions use different blocks.
Most likely your friends have devices with an older version of HW while you have a newer one that uses the second block.

**Comment by Keba4** [comment]
Thank you very much, it helped!
