### ISSUE TITLE
[REQUEST] adding support for the SMOK primus kooper

### ISSUE THREAD

**Issue by nextcode4u** [TBXin/NFirmwareEditor#60]
its a feature rich vape but could definitely add more features and graphics the hex file is easy to achieve download the smok upgrade tool and selecting the primus kooper and clicking check for update downloads the hex file for the device in the same folder for as the upgrade tool would love to see some support as I've used this tool to add custom graphics to my own and many friends rx200 and 200s keep up the good work [http://www.smoktech.com/hotnews/products/koopor-primus-firmware-upgrade-guide (upgrade tool)

**Comment by TBXin** [comment]
Thanks for your suggestion, 
but i think that it is not appropriate to the NFE, because NFE is a Joyetech's firmware editor, not SMOK, Evolv and so on.
