### ISSUE TITLE
Bricked Rx200 :OO?!?

### ISSUE THREAD

**Issue by Kombohead** [TBXin/NFirmwareEditor#67]
Hi since i updatet the secons ( s when firing ) into this flame icon and updating the rx200s it crasehd and is now black the update tool also crashes....... what can i do 
![unbenannt](https://cloud.githubusercontent.com/assets/21246409/18008023/cb7658ca-6ba6-11e6-86d0-fef33f20fa8b.png)

**Comment by Kombohead** [comment]
fixed it self sry

**Comment by TBXin** [comment]
Hello,

You can upload original or custom working firmware when device is in the safe mode.

1. Take out batteries;
2. Press + button and hold;
3. Connect to the USB;
4. Release + button;
5. Open NFE Flasher or Wismec ;
6. Device will recognized with Firmware version: 0.00;
7. Upload firmware;
8. Profit;

**Comment by Kombohead** [comment]
thanx!!!!
can i also somehow change the layout of the screen ?

**Comment by TBXin** [comment]
There are no simple way to do this.
Only way is modifing executable code of the firmware. This is a complex task.

**Comment by Kombohead** [comment]
ok so i cant e.g insert a fullsice logo instead of loading symbol ?

**Comment by TBXin** [comment]
You can safely replace any glyph with your own image without changing glyph size.
Also, you can decrease original glyph size, but you can't increase it size without creating patch, that will relocate original glyph to the other space in the firmware.

**Comment by Kombohead** [comment]
ok ty so no bigger Logos for Noah :D (me)
