### ISSUE TITLE
Compile NFE from Source

### ISSUE THREAD

**Issue by bluenazgul** [TBXin/NFirmwareEditor#69]
Do I need anything else to Visual Studio 2015? To get NFE build with downloaded Github Source?

**Comment by TBXin** [comment]
Nope, only VS 2015 to build project from sources.

**Comment by Bidulglloq** [comment]
Might it work from mac, e.g. installing VS2015 for mac and compiling the sources?
-or does your source code contains MSwindows specific code, preventing porting it to Mac OS?

**Comment by TBXin** [comment]
@Bidulglloq 
1. There are no any VS for mac
2. Yes, UI is all windows-specific, other code can be ported.

**Comment by Bidulglloq** [comment]
Sad for that...
Any plans for a mac version? ;)

**Comment by TBXin** [comment]
@Bidulglloq unfortunately no, but you can try to run NFE with WINE, also you can use Parallels / VirtualBox to install windows and use NFE.
