### ISSUE TITLE
rx200 Bitmaps

### ISSUE THREAD

**Issue by applehat** [TBXin/NFirmwareEditor#7]
The editor doesn't appear to allow the edit of the 0xA block of bitmaps.

There is a patch available for the RX200 3.1 firmware that says "show the 0xA2 splash screen" but I can't actually modify the 0xA2 block.

**Comment by TBXin** [comment]
Hello,
Can you explain in more details?
I tested this patch and successfully changed the image for it.

**Comment by applehat** [comment]
I apologize. I just realized this is an issue on my end.

I have been running the tool inside Wine on OSX - and it works great, but the block selector doesn't seem to scale correctly in Wine (not an issue with your code).

![screen shot 2016-04-18 at 11 24 44 am](https://cloud.githubusercontent.com/assets/262524/14611515/418feefa-0558-11e6-8e3f-bb640e0045f5.png)

I realize now if I use my keyboard I can keep going down to more blocks (off screen).

![screen shot 2016-04-18 at 11 25 51 am](https://cloud.githubusercontent.com/assets/262524/14611527/535f888e-0558-11e6-8fcb-bdd9ad94f5b2.png)

You can disregard this issue. Sorry again.

**Comment by TBXin** [comment]
No problem :)
I recommend you use Parallels Desktop instead of Wine. Coherence mode is awesome!

**Comment by applehat** [comment]
At home I have a Virtual Box instance with windows installed, but at work I dont... so I decided to see how it worked with wine =).

**Comment by maelstrom2001** [comment]
`winetricks dotnet40` and everything will work like a charm )
