### ISSUE TITLE
rx200s firmware not being able to load

### ISSUE THREAD

**Issue by shadowfate7** [TBXin/NFirmwareEditor#70]
ive been trying to load my firmware and the program wont open it keeps saying no one definition and then ive tried to load the new patch for the 4.12 firmware and it keeps saying error XML document 
(1036, 1)

**Comment by TBXin** [comment]
Look here, there is definitions for RX200S 4.02 / 4.12 firmwares
https://github.com/TBXin/NFirmwareEditor/issues/64

**Comment by shadowfate7** [comment]
i did add it

**Comment by shadowfate7** [comment]
[log.txt](https://github.com/TBXin/NFirmwareEditor/files/453466/log.txt)

**Comment by TBXin** [comment]
Special for you and others who can't edit xml files there is completed file.
