### ISSUE TITLE
[Request] Definitions for Cuboid 5.04 / 5.14, Cuboid Mini 5.04, eGrip II 5.04, eVic AIO 5.04, eVic VTC Mini 5.04, eVic VTwo 5.04, eVic VTwo Mini 5.04

### ISSUE THREAD

**Issue by SuperMidgetProductions** [TBXin/NFirmwareEditor#71]
These were released recently.

**Comment by TBXin** [comment]
Add to your definitions.xml following

For **Evic VTC Mini 5.04**

    <FirmwareDefinition Name="Evic VTC Mini 5.04">
    	<Marker Offset="0x90" Bytes="0x5D 0x1E" />
    	<Marker Offset="0xC0" Bytes="0xFD 0x79" />
    	<ImageTable1>
    		<OffsetFrom>0xD298</OffsetFrom>
    		<OffsetTo>0xD6A8</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xB27C</OffsetFrom>
    		<OffsetTo>0xB68C</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0xD7AC</OffsetFrom>
    		<OffsetTo>0xD9A3</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **Evic VTwo 5.04**

    <FirmwareDefinition Name="Evic VTwo 5.04">
    	<Marker Offset="0x90" Bytes="0xF5 0x2A" />
    	<Marker Offset="0xC0" Bytes="0x45 0x93" />
    	<ImageTable1>
    		<OffsetFrom>0x102E8</OffsetFrom>
    		<OffsetTo>0x10710</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xDC6C</OffsetFrom>
    		<OffsetTo>0xE094</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0x10814</OffsetFrom>
    		<OffsetTo>0x10A8F</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **Evic VTwo Mini 5.04**

    <FirmwareDefinition Name="Evic VTwo Mini 5.04">
    	<Marker Offset="0x90" Bytes="0x69 0x2B" />
    	<Marker Offset="0xC0" Bytes="0xA1 0x98" />
    	<ImageTable1>
    		<OffsetFrom>0x108C4</OffsetFrom>
    		<OffsetTo>0x10CEC</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xE248</OffsetFrom>
    		<OffsetTo>0xE670</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0x10DF0</OffsetFrom>
    		<OffsetTo>0x1108D</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **Cuboid 5.04**

    <FirmwareDefinition Name="Cuboid 5.04">
    	<Marker Offset="0x90" Bytes="0x55 0x22" />
    	<Marker Offset="0xC0" Bytes="0x11 0x7E" />
    	<ImageTable1>
    		<OffsetFrom>0xD67C</OffsetFrom>
    		<OffsetTo>0xDA8C</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xB660</OffsetFrom>
    		<OffsetTo>0xBA70</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0xDB90</OffsetFrom>
    		<OffsetTo>0xDDE9</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **Cuboid 5.14**

    <FirmwareDefinition Name="Cuboid 5.14">
    	<Marker Offset="0x90" Bytes="0x55 0x22" />
    	<Marker Offset="0xC0" Bytes="0x01 0x7E" />
    	<ImageTable1>
    		<OffsetFrom>0xD66C</OffsetFrom>
    		<OffsetTo>0xDA7C</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xB650</OffsetFrom>
    		<OffsetTo>0xBA60</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0xDB80</OffsetFrom>
    		<OffsetTo>0xDDD9</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **Cuboid Mini 5.04**

    <FirmwareDefinition Name="Cuboid Mini 5.04">
    	<Marker Offset="0x90" Bytes="0xA1 0x1D" />
    	<Marker Offset="0xC0" Bytes="0x99 0x74" />
    	<ImageTable1>
    		<OffsetFrom>0xCCB0</OffsetFrom>
    		<OffsetTo>0xD0C0</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xAC94</OffsetFrom>
    		<OffsetTo>0xB0A4</OffsetTo>
    	</ImageTable2>		
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0xD1C4</OffsetFrom>
    		<OffsetTo>0xD399</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **eVic AIO 5.04**

    <FirmwareDefinition Name="eVic AIO 5.04">
    	<Marker Offset="0x90" Bytes="0x29 0x2B" />
    	<Marker Offset="0xC0" Bytes="0x11 0x96" />
    	<ImageTable1>
    		<OffsetFrom>0x105B4</OffsetFrom>
    		<OffsetTo>0x109DC</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xDF38</OffsetFrom>
    		<OffsetTo>0xE360</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0x10AE0</OffsetFrom>
    		<OffsetTo>0x10DC7</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>


For **eGrip II 5.04**

    <FirmwareDefinition Name="eGrip II 5.04">
    	<Marker Offset="0x90" Bytes="0x21 0x2B" />
    	<Marker Offset="0xC0" Bytes="0x21 0x96" />
    	<ImageTable1>
    		<OffsetFrom>0x105C4</OffsetFrom>
    		<OffsetTo>0x109EC</OffsetTo>
    	</ImageTable1>
    	<ImageTable2>
    		<OffsetFrom>0xDF48</OffsetFrom>
    		<OffsetTo>0xE370</OffsetTo>
    	</ImageTable2>
    	<StringTable1 TwoByteChars="true">
    		<OffsetFrom>0x10AF0</OffsetFrom>
    		<OffsetTo>0x10DD1</OffsetTo>
    	</StringTable1>
    	<CharsToCorrect>0x88 0x91 0x9A</CharsToCorrect>
    </FirmwareDefinition>

**Comment by SuperMidgetProductions** [comment]
Thank you

**Comment by mirko93s** [comment]
Are the 4.02 patches compatible with 5.02 firmware?

**Comment by TBXin** [comment]
@mirko93s no
