### ISSUE TITLE
myevic

### ISSUE THREAD

**Issue by ClockSelect** [TBXin/NFirmwareEditor#72]
About:
https://github.com/ClockSelect/myevic

After system vectors, at offset 0x140, myevic firware will contain:

0x140: "MYFW" (0x5746594D)

0x144: Pointer to start of picture table block 1
0x148: Pointer to end of picture table block 1
0x14C: Pointer to start of picture table block 2
0x150: Pointer to end of picture table block 2
0x154: Pointer to first string
0x158: Pointer to end of last string+1

Would it help make it editable?

**Comment by TBXin** [comment]
Hello,

Thanks for the pointers. This is cool feature, that allowing to use only one definition for every version of myEvic firmwares.

I will add support to the NFE soon.

**Comment by ClockSelect** [comment]
Great, thanks :)

**Comment by TBXin** [comment]
@ClockSelect released NFE 4.1 with your firmwares support.
https://github.com/TBXin/NFirmwareEditor/releases/tag/4.1

**Comment by ClockSelect** [comment]
Awsome!
Grats!
