### ISSUE TITLE
Unable to load Firmware

### ISSUE THREAD

**Issue by AndyLiebe** [TBXin/NFirmwareEditor#73]
A Info comes:

Unable to load Firmware .
No one definition is not appropriate for the selected firmware file.

When I load the 5.04 from Joyetech for my eGrip II
![fehler](https://cloud.githubusercontent.com/assets/10630215/18340001/eb7d75e4-75a2-11e6-887a-d59e8a647840.png)

**Comment by TBXin** [comment]
Oh, i see, Joyetech again released new binary file with a same version. 
I will add new definitions soon in the repo.

**Comment by TBXin** [comment]
Just added new definitions in the repo.

![](http://i.imgur.com/T3HMhZf.png)

**Comment by AndyLiebe** [comment]
thx a lot!
