### ISSUE TITLE
[REQUEST] definizione for 4.04 evic aio

### ISSUE THREAD

**Issue by deddy84** [TBXin/NFirmwareEditor#75]
Please, can you add support to 4.04 evic aio?

**Comment by TBXin** [comment]
Already done.

**Comment by deddy84** [comment]
Thanks, for 5.04 definition
but i want to open 4.04 evic aio firmware. nfirmwareeditor say: unable to load firmware. No one definition is not appropriate for the selected  firmware file.

**Comment by TBXin** [comment]
Oh, i see.

**Comment by TBXin** [comment]
Restart NFE to get eVic AIO 4.04 support.

![](http://i.imgur.com/grukb1O.png)

**Comment by deddy84** [comment]
2 words: THANK YOU!

**Comment by deddy84** [comment]
Don't find big clock screensaver, so i'm unable to import from my old custom firmware.

**Comment by TBXin** [comment]
![](http://i.imgur.com/kZWuoKA.png)

**Comment by deddy84** [comment]
Sorry, but that is the small clock in power mode. 
Please check 4.02: at the bottom of the list was another bigger watch, which was the screen saver.

**Comment by TBXin** [comment]
Can you provide screenshot with big clock? I dont see them in the firmware.
Also, at the screenshot that i provided - opened 4.02 and 4.04 firmwares and there are no big clocks...

**Comment by TBXin** [comment]
Oh. It's my bad. A little mistake in the firmware reading code. I wll create new NFE release soon.

**Comment by deddy84** [comment]
A BIG THANKS AGAIN! :)

**Comment by TBXin** [comment]
Done.
![](http://i.imgur.com/5MCHu5B.png)

![](http://i.imgur.com/RHz7iJp.png)
