### ISSUE TITLE
[REQUEST] Pre-heat patch for 4.02 VTwo mini

### ISSUE THREAD

**Issue by Johnny147** [TBXin/NFirmwareEditor#77]
Hello,
I found a modded firmware with the pre-heat function.
https://github.com/ClockSelect/myevic

I'd like to add the same function for my 4.02 firmware that would be awesome.

Thanks !

**Comment by TBXin** [comment]
Hello,

Why you don't want to use myEvic firmware with preheat function?

**Comment by Johnny147** [comment]
Thanks for reply, because I actually have a modded (Digital Clock 4.02) firmware that shows me time and date when ON + as screensaver. I can't have neither this date on myEvic firmware
(I tried to transfer incompatibles patchs files... learned I know nothing to programmation)

**Comment by Johnny147** [comment]
ClockSelect did it ! Thanks :)
