### ISSUE TITLE
[Request] RX200S 4.12 Patches

### ISSUE THREAD

**Issue by Restless89** [TBXin/NFirmwareEditor#78]
Hi is it possible to get patches for 100% brightness, SS temp fix and 1W increments for the 4.12 update
or is it possible to use the 4.10 patch files?
Thanks.

**Comment by SEEKNDESTROY** [comment]
Also the cutoff voltage patch, please.
![untitled](https://cloud.githubusercontent.com/assets/22176387/18481643/e669a3a0-79aa-11e6-9f6b-cf3070f71987.jpg)

**Comment by RenegadeTitan** [comment]
@TBXin please add:
rx200s FW4.12:

[SS_tc_fix.txt](https://github.com/TBXin/NFirmwareEditor/files/473749/SS_tc_fix.txt)

**Comment by RenegadeTitan** [comment]
@TBXin another one for you:
rx200s FW4.12:

[1W Step.txt](https://github.com/TBXin/NFirmwareEditor/files/475518/1W.Step.txt)

**Comment by Restless89** [comment]
Thanks^

**Comment by SEEKNDESTROY** [comment]
Thanks Renegade...much appreciated!
