### ISSUE TITLE
Вводится текст в поля для чтения

### ISSUE THREAD

**Issue by Yoti** [TBXin/NFirmwareEditor#79]
Есть возможность ввода текста на вкладке "Patches", в поле "Incompatibility with patches" (правый нижний угол). Если там уже есть какой-либо текст, его можно стереть/изменить. Аналогично себя ведёт "Resource packs" -> "Description" (низ окна). Я так понимаю, так не было задумано by design =)

**Comment by TBXin** [comment]
Спасибо за информацию. Да, это неправильное поведение.

**Comment by TBXin** [comment]
Fixed: https://github.com/TBXin/NFirmwareEditor/commit/8cce31364454e9fbbe198efaa8709272dd5d7971
