### ISSUE TITLE
RX200 broken after Flash with internal Firmware Updater

### ISSUE THREAD

**Issue by hitme666** [TBXin/NFirmwareEditor#8]
My RX200 is broken after flashing it to 3.10 with internal Firmware Updater.
My my dosn't reconioze it as USB device anymore, Display stays black also, no matter what i try.

pc only showing "USB\DEVICE_DESCRIPTOR_FAILURE" in device managment.

**Comment by TBXin** [comment]
Hello, 
Probably are you're somehow damaged the firmware file, for example - trying to insert a larger image than it was.

You need to take off batteries from your RX, press PLUS button and hold, then connect to usb and release plus button. Device will identify with FW version: 0.00.
Now you can upload correct firmware file.

**Comment by hitme666** [comment]
Hi, that helped!

Is there a way thats the internal Firmware Updater checks the firmware before flashing it?

**Comment by TBXin** [comment]
Unfortunately no.  NFE can't validate firmware code blocks.
NFE validates only that firmware is you trying to upload is satisfy device.

**Comment by hitme666** [comment]
wenn, anyway thank you for all your affords! ;)
