### ISSUE TITLE
Same patch in evic aio

### ISSUE THREAD

**Issue by NasosGR** [TBXin/NFirmwareEditor#80]
Hello there, I have an Evic Aio and i would like the Digital Clock and Date on Big clock screen( the screensaver) patch on that kit. Now i dont have a clue about proigramming and it took me long enought to get here. I found firmware editor and saw I can aply patches to firmwares. So now I am looking how can I add that patch on my Evic Aio Software. Please help me. My email is N.tsimpliaridis@gmail.com

**Comment by TBXin** [comment]
Hello,

There are no patches available for eVic AIO firmwares. 
No plans to porting patches. So, your only hope wait when someone will create patches for your device firmwares.

**Comment by NasosGR** [comment]
But the firmwares are more or less all the same, isnt there anyway I can import the patch to the evic aio firmware?

**Comment by TBXin** [comment]
This is not true. You can make such a conclusion only as a user, but at the binary level each firmware is almost unique.
Thats why anyone can not create patches without disassembling firmwares to the ASM.

**Comment by NasosGR** [comment]
I understand... Look I am sorry if I am wasting your time but I am really determined to make this work, is there any way I can contact you via email or something?

**Comment by TBXin** [comment]
Unfortunately i can not help you with patches. I can recommended to you read this: https://github.com/TBXin/NFirmwareEditor/issues/49
There are some little guide how to port patches.
