### ISSUE TITLE
[REQUEST] Wismec RX2/3

### ISSUE THREAD

**Issue by l4bor** [TBXin/NFirmwareEditor#82]
How to lower the minimum threshold limit resistance 1 Ohm to 0.05 Ohm?

**Comment by TBXin** [comment]
RX2/3 can do this out of the box.
0.1 Ohm for VW, and 0.05 Ohm for TC coils.

**Comment by l4bor** [comment]
and in the VW mode?

**Comment by l4bor** [comment]
I would like to know whether it is possible to make a patch to reduce the threshold limit for VW-mode to 0,05om

**Comment by alexrezv** [comment]
I think he ment modifying 0.1 Ohm limit to 0.05 in VW

**Comment by TBXin** [comment]
for your own safety - no.

**Comment by alexrezv** [comment]
F**k safety, bro) is it possible? At least in theory

**Comment by TBXin** [comment]
F*ck or not - it is not for you to decide.

**Comment by l4bor** [comment]
Ok, thanks dude!
