### ISSUE TITLE
[5.0][Config Editor] Preheat Power

### ISSUE THREAD

**Issue by ClockSelect** [TBXin/NFirmwareEditor#83]
Preheat Power should multiplied by 10 when uploaded (Tenth of Watt).

**Comment by TBXin** [comment]
Thanks, fixed in d9b3315fc6b591e05268080b4700506574d4faa6

**Comment by TBXin** [comment]
I think we should harmonize dataflash structure in the development stage. I mean before another release.
It would be nice if we are able to communicate in some chat, bypassing the forums or github issues.

**Comment by ClockSelect** [comment]
Agree.
I'm permanently connected to the ##evic-modding chan of Freenode, it's a way.

**Comment by TBXin** [comment]
Fixed in release 5.01.
