### ISSUE TITLE
[5.0][Config Editor] Selected TCR Index

### ISSUE THREAD

**Issue by ClockSelect** [TBXin/NFirmwareEditor#84]
The selected TCR index (M1,2,3) is correctly decoded only when TCR mode is selected.
If not, the editor will send a random index value when uploading config.

**Comment by TBXin** [comment]
Fixed in 71a380b2c23f591a3fe661e2a7e4374074c8091c

**Comment by TBXin** [comment]
Fixed in release 5.01.
