### ISSUE TITLE
myEvic NFE Edition

### ISSUE THREAD

**Issue by bluenazgul** [TBXin/NFirmwareEditor#85]
I think there should also be an Option to check for a New release (latest release) of myEvic NFE Edition inside NFirmwareEditor or maybe an Updater.

Also I think it could be possible to set an own Version Number in myEvic NFE Edition inside the sourcecode. 

This would make it easy to check for updates.

**Comment by TBXin** [comment]
Hello,

Thanks for your suggestion.
Our unique version is already there, it is called build and you can see it in the configuration window.
We will think about checking for firmware updates.
