### ISSUE TITLE
[Request] Export/import mod settings

### ISSUE THREAD

**Issue by Dareksa** [TBXin/NFirmwareEditor#86]
Is it possible to add export/import mod settings via NFE Edition-Configuration ?

**Comment by TBXin** [comment]
Hello,

Yes, it possible, but what kind of settings do you want to export/import?
If you don't want to share settings with other people you can save the dataflash via Firmware Updater.
Dataflash contains all settings and other system stuff like HWVer.
So, if you save dataflash from your device later you can safely wirte this dataflash back to your device.

**Comment by Dareksa** [comment]
Hello,

I had in mind export settings from one device to another, for example, from VTC mini to vtwo mini.
I use both models in parallel and at the moment I have to set them up separately.

**Comment by TBXin** [comment]
Okay, i understood you.
Will see what i can do.
