### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by TBXin** [TBXin/NFirmwareEditor#89]
**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by Teerapong2534** [comment]
![15310500_232813627150446_995201292_n](https://cloud.githubusercontent.com/assets/23415935/20835165/ad6f93ce-b8cb-11e6-8435-261c7e99efda.jpg)
Rx 2.3  
Came with a plan not connect usb

**Comment by Teerapong2534** [comment]
Help came with a plan with a USB RX2.3 not.
