### ISSUE TITLE
"Save Screenshot" should not Take Screenshot.

### ISSUE THREAD

**Issue by ClockSelect** [TBXin/NFirmwareEditor#92]
The "Save Screenshot" function should save the screenshot already taken, and not take a new screenshot on the fly.

**Comment by TBXin** [comment]
There are checkbox, that gives behavior as you want.

![](http://i.imgur.com/S0xV89N.png)

**Comment by ClockSelect** [comment]
Oh, missed it. Seem to be related to the pixel size multiplier.

**Comment by TBXin** [comment]
Yeah, not best placement for this option.

**Comment by ClockSelect** [comment]
This option is a bit useless anyway, no?

**Comment by TBXin** [comment]
I am used it when creating a series of screenshots.
Click -> Enter, Click -> Enter, etc.

I think i should change default behavior, and unckeck this checkbox.
