### ISSUE TITLE
myEvic NFE Edition not recognizing my device

### ISSUE THREAD

**Issue by SEEKNDESTROY** [TBXin/NFirmwareEditor#99]
Issue Descriptions: myEvic NFE Edition not recognizing my device
OS: Windows 10 (10.0.10586 Build 10586)
Mod = RX200S
Latest myEvic firmware installed
Expert Settings:
USB set to COM
NFE = On
UCH = Off

Steps to Reproduce:
1. Load latest myEvic firmware in NFirmwareEditor v.5.1
2. Plug in RX200S
3. Select "Device Configuration" - All I get is "_Waiting for device with myEvic NFE Edition 161002 or newer_"
4. Select "Device Monitor" says "_No compatible USB devices are connected. To continue, please connect one. If one already IS connected, try unplugging and plugging it back in. The cable may be loose._"
I follow the instructions, click OK and the same message. I click cancel and NFirmwareEditor stops working/crashes.

![untitled](https://cloud.githubusercontent.com/assets/22176387/19931191/f8db00c0-a0e1-11e6-86bf-edd258c10f7a.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/22176387/19931190/f8d6a520-a0e1-11e6-99f5-3beba83b772a.jpg)
![untitled3](https://cloud.githubusercontent.com/assets/22176387/19931192/f8dd6f72-a0e1-11e6-9dba-9ccabaa30731.jpg)

I hope this helps.

**Comment by TBXin** [comment]
Hello,

> Latest myEvic firmware installed

Waiting for device with myEvic **NFE Edition**

**Comment by SEEKNDESTROY** [comment]
Hi TBXin,
Thank you for your quick reply.
My installed firmware is 161030 which should be newer than 161002, right?

**Comment by TBXin** [comment]
Yep, 161030 is newer than 161002, but i mean that "myEvic" is not "myEvic NFE Edition". This is two different firmwares, and NFirmwareEditor (NFE) will work only with "myEvic NFE Edition"

**Comment by SEEKNDESTROY** [comment]
Gotcha! Thanks for clarifying and sorry for the trouble.
